;;;; utz-light-theme.el --- My lightest theme
;;; Commentary:
;;
;; How light can it get?
;;
;;; Code:
(deftheme utz-light)

(let ((bg "#e3e1ee")
      (fg "#130e21")
      (c0 "#251d38")
      (c1 "#382f4f")
      (c2 "#413661")
      (c3 "#62538d")
      (c4 "#806fb2")
      (c5 "#9185bb")
      (c6 "#b8b0d3")
      (c7 "#c9c3de")
      (c8 "#e977ba")
      (c9 "#f7aad4")
      (c10 "#8e9a3c")
      (c11 "#ed8cc4")
      (c12 "#68b897")
      (c13 "#ae99ee")
      (c14 "#3793c8")
      (c15 "#d8895e"))
  (custom-theme-set-faces
   'utz-light
   `(company-scrollbar-bg ((t (:background ,c2))))
   `(company-scrollbar-fg ((t (:background ,c4))))
   `(company-tooltip ((t (:background ,c0 :foreground ,c6))))
   `(company-tooltip-annotation ((t (:foreground ,c8))))
   `(company-tooltip-mouse ((t (:inherit mode-line-highlight))))
   `(company-tooltip-common ((t (:background ,c1 :foreground ,c7))))
   `(company-tooltip-common-selection ((t (:inherit region))))
   `(company-tooltip-search ((t (:inherit isearch))))
   `(company-tooltip-search-selection ((t (:inherit lazy-highlight))))
   `(company-tooltip-selection ((t (:inherit region))))
   `(default ((t (:background ,bg :foreground ,fg))))
   `(evil-ex-substitute-matches ((t (:background ,c15 :foreground ,c2 :strike-through ,c2))))
   `(evil-ex-substitute-replacement ((t (:background ,c2 :foreground ,c15))))
   `(font-lock-builtin-face ((t (:foreground ,c11))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,c3))))
   `(font-lock-comment-face ((t (:foreground ,c5))))
   `(font-lock-function-name-face ((t (:foreground ,c14))))
   `(font-lock-keyword-face ((t (:foreground ,c14 :weight bold))))
   `(font-lock-string-face ((t (:foreground ,c15 :weight bold))))
   `(font-lock-type-face ((t (:foreground ,c14))))
   `(font-lock-variable-name-face ((t (:foreground ,c13))))
   `(fringe ((t (:inherit line-number))))
   `(header-line ((t (:background ,bg :foreground ,c4))))
   `(helm-M-x-key ((t (:inherit org-link))))
   `(helm-action ((t (:inherit org-link))))
   `(helm-selection ((t (:inherit region))))
   `(helm-source-header ((t (:inherit (outline-1)))))
   `(hl-line ((t (:foreground ,c2 :background ,c15))))
   `(isearch ((t (:foreground ,bg :background ,c9))))
   `(lazy-highlight ((t (:foreground ,c15 :background ,c1))))
   `(line-number ((t (:background ,c7 :foreground ,c4))))
   `(line-number-current-line ((t (:background ,c15 :foreground ,bg))))
   `(magit-section-heading ((t (:inherit outline-1))))
   `(minibuffer-prompt ((t (:foreground ,c14))))
   `(mode-line ((t (:background ,c5 :foreground ,bg))))
   `(mode-line-highlight ((t (:background ,c15 :foreground ,fg))))
   `(mode-line-inactive ((t (:background ,c7 :foreground ,c5))))
   `(org-block ((t (:background ,bg :foreground ,fg))))
   `(org-block-begin-line ((t (:foreground ,c4 :background ,bg))))
   `(org-block-end-line ((t (:inherit org-block-begin-line))))
   `(org-drawer ((t (:foreground ,c4))))
   `(org-level-1 ((t (:inherit outline-1 :height 2.2))))
   `(org-level-2 ((t (:inherit outline-2 :height 2.0))))
   `(org-level-3 ((t (:inherit outline-3 :height 1.8))))
   `(org-level-4 ((t (:inherit outline-4 :height 1.6))))
   `(org-level-5 ((t (:inherit outline-1 :height 1.4))))
   `(org-level-6 ((t (:inherit outline-2 :height 1.2))))
   `(org-level-7 ((t (:inherit outline-3 :height 1.1))))
   `(org-level-8 ((t (:inherit outline-4 :height 1.0))))
   `(org-link ((t (:foreground ,c12))))
   `(org-special-keyword ((t (:foreground ,c9))))
   `(org-tag ((t (:height 0.6 :foreground ,c3))))
   `(outline-1 ((t (:foreground ,c14))))
   `(outline-2 ((t (:foreground ,c13))))
   `(outline-3 ((t (:foreground ,c8))))
   `(outline-4 ((t (:foreground ,c12))))
   `(powerline-active1 ((t (:background ,c14 :foreground ,bg))))
   `(powerline-active2 ((t (:background ,c7))))
   `(powerline-inactive1 ((t (:background ,bg :foreground ,c5))))
   `(powerline-inactive2 ((t (:background ,bg :foreground ,c5))))
   `(query-replace ((t (:background ,c15 :foreground ,c2))))
   `(region ((t (:foreground ,bg :background ,c12))))
   `(show-paren-match ((t (:foreground ,bg :background ,c11))))
   `(spaceline-evil-emacs ((t (:foreground ,bg :background ,c8))))
   `(spaceline-evil-insert ((t (:foreground ,bg :background ,c12))))
   `(spaceline-evil-motion ((t (:foreground ,bg :background ,c14))))
   `(spaceline-evil-normal ((t (:foreground ,fg :background ,c15))))
   `(spaceline-evil-replace ((t (:foreground ,bg :background ,c13))))
   `(spaceline-evil-visual ((t (:foreground ,bg :background ,c6))))
   `(vertical-border ((t (:foreground ,c7))))))

(provide 'utz-light)
;;; utz-light-theme.el ends here
