gui:
  expandFocusedSidePanel: true
  showRandomTip: false
  showCommandLog: true
  showBottomLine: false
  nerdFontsVersion: "3"
  border: rounded
git:
  parseEmoji: true
  commit:
    signOff: true
  paging:
    colorArg: always
    pager: delta --paging=never
notARepository: skip
promptToReturnFromSubprocess: false
disableStartupPopups: true
customCommands:
  - key: b
    context: files
    command: aicommits
    description: aicommits
    subprocess: true
    showOutput: true
  - key: z
    command: git cz c
    description: commit with commitizen
    context: files
    loadingText: opening commitizen commit tool
    subprocess: true
  - key: E
    description: Add empty commit
    context: commits
    command: 'git commit --allow-empty -m "chore: empty commit"'
    loadingText: Committing empty commit...
