customCommands:
  - command: oco
    context: files
    description: opencommit
    key: b
    showOutput: true
    subprocess: true
disableStartupPopups: true
git:
  commit:
    signOff: true
  paging:
    colorArg: always
    pager:
      'delta "$(dark-mode status | grep on && echo "--dark" || echo "--light")"
      --paging=never
      '
  parseEmoji: true
  overrideGpg: true
gui:
  border: rounded
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  showBottomLine: false
  showCommandLog: true
  showRandomTip: false
notARepository: skip
promptToReturnFromSubprocess: false
