abbr -a -- gco 'git checkout'
abbr -a -- c chezmoi
abbr -a -- cmsw 'chezmoi status-watch'
abbr -a -- cmd 'chezmoi diff'
abbr -a -- cmra 'chezmoi re-add'
abbr -a -- gws 'git status --short'
abbr -a -- cmcd 'chezmoi cd'
abbr -a -- cmsa 'chezmoi status-all'
abbr -a -- cms 'chezmoi status-all'
abbr -a -- cmS 'chezmoi status'
abbr -a -- cme 'chezmoi edit'
