abbr -a -- gco 'git checkout'
abbr -a -- c chezmoi
abbr -a -- cmsw 'chezmoi status-watch'
abbr -a -- cmd 'chezmoi diff'
abbr -a -- cmra 'chezmoi re-add'
abbr -a -- gws 'git status --short'
abbr -a -- cmcd 'chezmoi cd'
abbr -a -- cmsa 'chezmoi status-all'
abbr -a -- cms 'chezmoi status-all'
abbr -a -- cmS 'chezmoi status'
abbr -a -- cme 'chezmoi edit'
abbr -a -- cmew 'chezmoi edit --watch'
abbr -a -- cmea 'chezmoi edit --apply'
abbr -a -- cmap 'chezmoi apply'
abbr -a -- cmma 'chezmoi merge-all'
abbr -a -- cmfzfa 'cmfzf | xargs chezmoi add'
abbr -a -- lg lazygit
abbr -a -- cma 'chezmoi add'
abbr -a -- md 'mkdir -p'
abbr -a -- gfm 'git pull'
abbr -a -- gpp 'git pull && git push'
abbr -a -- brews 'brew search'
abbr -a -- cmad 'chezmoi add-deleted'
abbr -a -- brewi 'brew install'
abbr -a -- caski 'brew install --cask'
abbr -a -- brewx 'brew uninstall'
abbr -a -- mta 'mise tasks add'
