# [[manager.prepend_keymap]]
# on = ["<C-s>"]
# run = 'shell "nu" --block --confirm'
# desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["<C-g>"]
run = 'shell "lazygit" --block --confirm'
desc = "Open lazygit here"

[[manager.prepend_keymap]]
on = ["<C-c>"]
run = 'shell "chezmoi add $@" --block --confirm'
desc = "Add to chezmoi"
