[[manager.prepend_keymap]]
on = "!"
run = 'shell "/opt/homebrew/bin/fish" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["g", "l"]
run = 'shell "lazygit" --block --confirm'
desc = "Open lazygit here"

[[manager.prepend_keymap]]
on = ["g", "r"]
run = '''
  shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
'''
desc = "Jump to repo root"

[[manager.prepend_keymap]]
on = ["l"]
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[manager.prepend_keymap]]
on = ["g", "q"]
run = 'shell -- qlmanage -p "$@"'
desc = "Preview with QuickLook"

[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

[[manager.prepend_keymap]]
on = ["c", "h", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = ["c", "o"]
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[manager.prepend_keymap]]
on = ["c", "r"]
run = "plugin path-from-root"
desc = "Copies path from git root"

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = ["L"]
run = "plugin bypass"
desc = "Recursively enter child directory, skipping children with only a single subdirectory"

[[manager.prepend_keymap]]
on = ["c", "m", "a"]
run = 'shell "chezmoi add $@" --block'
desc = "Add files to chezmoi"

[[manager.prepend_keymap]]
on = ["c", "m", "A"]
run = 'shell "chezmoi apply --interactive $@" --block'
desc = "Apply files from chezmoi"

[[manager.prepend_keymap]]
on = ["c", "m", "c"]
run = 'shell "chezmoi  $@" --interactive --cursor=8; sleep 1h'
desc = "Run a chezmoi command on files"

[[manager.prepend_keymap]]
on = ["c", "m", "e"]
run = 'shell "chezmoi edit --watch $@" --block'
desc = "Edit files in chezmoi"

[[manager.prepend_keymap]]
on = ["c", "m", "f"]
run = 'shell "chezmoi forget $@" --block'
desc = "Forget files in chezmoi"

[[manager.prepend_keymap]]
on = ["c", "m", "m"]
run = 'shell "chezmoi merge $@" --block'
desc = "Merge files in chezmoi"

[[manager.prepend_keymap]]
on = ["c", "m", "r"]
run = 'shell "chezmoi re-add $@" --block'
desc = "Re-add files in chezmoi"

[[manager.prepend_keymap]]
on = ["c", "m", "s"]
desc = "Show chezmoi status"
run = '''
shell "chezmoi status .; sleep 30s" --block
'''

[[manager.prepend_keymap]]
on = ["c", "m", "x"]
run = 'shell "chezmoi destroy $@" --block'
desc = "Destroy files in chezmoi and home"
