[[manager.prepend_keymap]]
on = "!"
run = 'shell "/opt/homebrew/bin/fish" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["<C-g>"]
run = 'shell "lazygit" --block --confirm'
desc = "Open lazygit here"

[[manager.prepend_keymap]]
on = ["g", "r"]
run = '''
  shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
'''
desc = "Jump to repo root"

[[manager.prepend_keymap]]
on = ["l"]
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[manager.prepend_keymap]]
on = "<C-p>"
run = 'shell -- qlmanage -p "$@"'
desc = "Preview with QuickLook"
