[[manager.prepend_keymap]]
on = "!"
run = 'shell "/opt/homebrew/bin/fish" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["g", "l"]
run = 'shell "lazygit" --block --confirm'
desc = "Open lazygit here"

[[manager.prepend_keymap]]
on = ["g", "r"]
run = '''
  shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
'''
desc = "Jump to repo root"

# [[manager.prepend_keymap]]
# on = ["l"]
# run = "plugin smart-enter"
# desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[manager.prepend_keymap]]
on = ["g", "q"]
run = 'shell -- qlmanage -p "$@"'
desc = "Preview with QuickLook"

[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = ["c", "o"]
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[manager.prepend_keymap]]
on = ["c", "r"]
run = "plugin path-from-root"
desc = "Copies path from git root"

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = ["L"]
run = "plugin bypass"
desc = "Recursively enter child directory, skipping children with only a single subdirectory"

[[manager.prepend_keymap]]
on = ["c", "h", "a"]
run = 'shell "chezmoi add $@" --block'
