#+TITLE: My Literate Emacs Config

* Define My Constants

  Of course, all of it begins here, in the file that was used to bootstrap this file:

  #+BEGIN_SRC emacs-lisp
    (defconst utz-emacs-init-file
      (expand-file-name "init.el" user-emacs-directory))
  #+END_SRC

  In the meantime, we'd like an easy way to refer to /this/ actual file.

  #+BEGIN_SRC emacs-lisp
    (defconst utz-emacs-config-file
      (or load-file-name buffer-file-name))
  #+END_SRC

  We won't be using the custom file, but we'd like to define it nonentheless. This way,
  we won't need to worry about any customizations messing up our config.

  #+BEGIN_SRC emacs-lisp
    (defconst utz-emacs-custom-file
      (expand-file-name ".custom.el" user-emacs-directory))
  #+END_SRC

  And we'd like a place to put our theme that we're so diligently building, of course.

  #+BEGIN_SRC emacs-lisp
    (defconst utz-emacs-theme-directory
      (expand-file-name "themes" user-emacs-directory))
  #+END_SRC

  #+BEGIN_SRC emacs-lisp
    (defconst utz-emacs-theme-file
      (expand-file-name "utz-theme.el" utz-emacs-theme-directory))
  #+END_SRC

* Define My Functions

** Narrow Page Navigation

   #+BEGIN_SRC emacs-lisp
     (defun utz/narrow-page-forward ()
       "Widen, forward, then narrow."
       (interactive)
       (widen)
       (forward-page)
       (narrow-to-page))

     (defun utz/narrow-page-backward ()
       "Widen, backward, then narrow."
       (interactive)
       (widen)
       (backward-page)
       (backward-page)
       (narrow-to-page))
   #+END_SRC

** Load and Edit Config Files

   #+BEGIN_SRC emacs-lisp
     (defun utz/load-config-file ()
       "Load configuration file all over again."
       (interactive)
       (org-babel-load-file utz-config-file))

     (defun utz/edit-config-file ()
       "Edit the configs."
       (interactive)
       (find-file utz-config-file))

     (defun utz/edit-theme-file (x)
       "Edit my custom theme. `C-u` visits it in customize."
       (interactive "p")
       (cond ((eq 4 x) (custom-theme-visit-theme 'utz))
	     (t (find-file utz-theme-file))))
   #+END_SRC

** Open Customize

   #+BEGIN_SRC emacs-lisp
     (defun utz/customize ()
       "Open the customize in another window."
       (interactive)
       (evil-window-vsplit)
       (customize))
   #+END_SRC

** Color Functions for Theme

   #+BEGIN_SRC emacs-lisp
     (defun utz/get-color (name)
       (let ((colors '((fg . "#c9c3de")
		       (bg . "#130e21")
		       (0 . "#1e1732")
		       (1 . "#281f3f")
		       (2 . "#392e59")
		       (3 . "#52437d")
		       (4 . "#705fa2")
		       (5 . "#9185bb")
		       (6 . "#b8b0d3")
		       (7 . "#e3e1ee")
		       (8 . "#e977ba")
		       (9 . "#f7aad4")
		       (10 . "#8e9a3c")
		       (11 . "#ed8cc4")
		       (12 . "#68b897")
		       (13 . "#ae99ee")
		       (14 . "#67c3d8")
		       (15 . "#f8a97e"))))
	 (cdr (assoc name colors))))
   #+END_SRC

* Configure Emacs

  #+BEGIN_SRC emacs-lisp
    (setq-default custom-file utz-emacs-custom-file)
    (setq-default custom-theme-directory utz-emacs-theme-directory)
  #+END_SRC

* [[https://github.com/noctuid/general.el][General.el]]

  [[./straight/repos/general.el/README.org][README]]

  #+BEGIN_SRC emacs-lisp
    (use-package general
      :config
      (general-create-definer utz/set-help-key
	:prefix "C-h")

      (general-create-definer utz/set-leader-key
	:prefix "SPC"
	:non-normal-prefix "M-SPC"
	:keymaps '(normal insert emacs visual))

      (general-create-definer utz/set-localleader-key
	:prefix ","
	:non-normal-prefix "M-,"))
  #+END_SRC

* Emacs

  #+BEGIN_SRC emacs-lisp
    (use-package emacs
      :hook ((before-save . delete-trailing-whitespace)
	     (emacs-lisp-mode . enable-paredit-mode))
      :init
      (show-paren-mode 1)
      (set-default-coding-systems 'utf-8-unix)
      (prefer-coding-system 'utf-8-unix)
      (menu-bar-mode 0)
      (scroll-bar-mode 0)
      (tool-bar-mode 0)

      (setq-default buffer-file-coding-system 'utf-8-unix)

      :custom
      (buffer-file-coding-system 'utf-8-unix)
      (locale-coding-system 'utf-8-unix)
      (inhibit-startup-screen t)
      (initial-scratch-message nil)
      (display-line-numbers 'relative)

      :config
      (load-theme 'utz t)

      :general
      ("s-," '(utz/customize :wk "Customize"))
      ("M-x" '(helm-M-x :wk "M-x"))
      (utz/set-help-key "" '(:ignore t :wk "Help")
	"f" '(helpful-callable :wk "Helpful Callable")
	"x" '(helpful-at-point :wk "Helpful At Point")
	"v" '(helpful-variable :wk "Helpful Variable")
	"k" '(helpful-key :wk "Helpful Key")
	"F" '(helpful-function :wk "Helpful Function")
	"c" '(helpful-command :wk "Helpful Command")))
(setq display-line-numbers 'visual)
  #+END_SRC

* Basic Settings

** Exec Path

   Make sure that emacs has access to all my homebrewy goodness.

   #+BEGIN_SRC emacs-lisp
     (setenv "PATH" (concat (getenv "PATH") ":/usr/local/bin"))
     (setq exec-path (append exec-path '("/usr/local/bin")))
   #+END_SRC

** Config files

   Setup some constants for my config file paths.

   #+BEGIN_SRC emacs-lisp
     (defconst utz-config-init (expand-file-name "init.el" user-emacs-directory))
     (defconst utz-config-file (expand-file-name "literally.org" user-emacs-directory))
     (defconst utz-custom-file custom-file)
     (defconst utz-themes-directory custom-theme-directory)
     (defconst utz-theme-file (expand-file-name "utz-theme.el" utz-themes-directory))
   #+END_SRC

   Load the custom file.

   #+BEGIN_SRC emacs-lisp
     (load utz-custom-file 'noerror 'nomessage)
   #+END_SRC

** Backup files

   #+BEGIN_SRC emacs-lisp
     (setq backup-directory-alist
	   `(("." . ,(concat user-emacs-directory "backups"))))
   #+END_SRC

** Allow "weird" functions

   Emacs thinks these would confuse people, and thus asks them if they want to use it. We don't like that.

   #+BEGIN_SRC emacs-lisp
     (put 'narrow-to-page 'disabled nil)
     (put 'narrow-to-defun 'disabled nil)
     (put 'narrow-to-region 'disabled nil)
   #+END_SRC

** Symlinks

   #+BEGIN_SRC emacs-lisp
     (setq vc-follow-symlinks t)
   #+END_SRC

* Keybindings

** Evil

   [[https://evil.readthedocs.io/en/latest][Evil]] sets up our vim-like keybindings.

   #+BEGIN_SRC emacs-lisp
     (use-package evil
       :init
       (setq evil-want-C-u-scroll t
	     evil-want-C-u-delete t
	     evil-shift-width 2
	     evil-indent-convert-tabs nil
	     evil-echo-state nil
	     evil-split-window-below t
	     evil-vsplit-window-right t
	     evil-normal-state-tag " NORMAL "
	     evil-visual-state-tag " VISUAL "
	     evil-insert-state-tag " INSERT "
	     evil-emacs-state-tag " EMACS "
	     evil-replace-state-tag " REPLACE "
	     evil-motion-state-tag " MOTION "
	     evil-want-keybinding nil)
       :config
       (evil-mode 1))
   #+END_SRC

*** Evil Magit

    A [[https://github.com/emacs-evil/evil-magit][plugin]] for making [[https://evil.readthedocs.io/en/latest/][Evil]] work with [[https://magit.vc/][Magit]]. Here's the [[file:straight/repos/evil-magit/README.org][README]].

    #+BEGIN_SRC emacs-lisp
      (use-package evil-magit
	:after evil magit)
    #+END_SRC

*** Evil Surround

    Emultate Tim Pope's VIM Surround plugin. [[./straight/repos/evil-surround/readme.org][README]]

    #+BEGIN_SRC emacs-lisp
      (use-package evil-surround
	:after evil
	:config
	(global-evil-surround-mode 1))
    #+END_SRC

*** Evil Commentary

    #+BEGIN_SRC emacs-lisp
      (use-package evil-commentary
	:after evil
	:config
	(evil-commentary-mode))
    #+END_SRC

*** Evil Collection

    #+BEGIN_SRC emacs-lisp
      (use-package evil-collection
	:after evil)
    #+END_SRC

*** Evil Org

    #+BEGIN_SRC emacs-lisp
      (use-package evil-org
	:diminish
	:after org
	:init
	(add-hook 'org-mode-hook 'evil-org-mode)
	(add-hook 'evil-org-mode-hook
		  (lambda ()
		    (evil-org-set-key-theme)))
	(require 'evil-org-agenda)
	(evil-org-agenda-set-keys))
    #+END_SRC

** Hydra

   #+BEGIN_SRC emacs-lisp
     (use-package hydra
       :defer 2)
   #+END_SRC

** Standard Keys

** `<leader>` Keys

*** Setup non-prefixed keys

    #+BEGIN_SRC emacs-lisp
      (utz/set-leader-key "SPC" '(helm-M-x :wk "M-x")
	"u" '(universal-argument :wk "Universal Argument")
	"0" '(ranger :wk "Ranger"))
    #+END_SRC

*** Setup "Git" prefix keys

    For when it's time to git it done.

    #+BEGIN_SRC emacs-lisp
      (utz/set-leader-key :infix "g"
	"" '(:ignore t :wk "Git")
	"s" 'magit-status
	"d" 'magit-dispatch)
    #+END_SRC

*** Setup "Files" prefix keys

    Fer filing stuff away.

    #+BEGIN_SRC emacs-lisp
      (utz/set-leader-key :infix "f"
	"" '(:ignore t :wk "Files")
	"s" 'save-buffer
	"f" 'helm-find-files
	"t" 'treemacs-select-window)

      (utz/set-leader-key :infix "f e"
	"" '(:ignore t :wk "Emacs Config")
	"R" 'utz/load-config-file
	"d" 'utz/edit-config-file
	"t" 'utz/edit-theme-file)
    #+END_SRC

*** Setup "Narrow / Widen" prefix keys

    Narrow, then widen. The circle of lifemacs.

    #+BEGIN_SRC emacs-lisp
      (utz/set-leader-key :infix "n"
	"" '(:ignore t :wk "Narrow / Widen")
	"." '(utz/hydra-narrow/body :wk "Transient State")
	"w" '(widen :wk "Widen")
	"p" '(narrow-to-page :wk "Narrow to Page")
	"r" '(narrow-to-region :wk "Narrow to Region")
	"d" '(narrow-to-defun :wk "Narrow to Function Definition")
	"]" '(utz/narrow-page-forward wk: "Next Page")
	"[" '(utz/narrow-page-backward wk: "Previous Page"))
    #+END_SRC

    Here's the hydra for the transient state:

    #+BEGIN_SRC emacs-lisp
      (defhydra utz/hydra-narrow (:hint nil)
	"
	^
	^Narrow^              ^Widen^    ^Navigate^
	^------^--------------^-----^----^--------^---------
	_p_ narrow to page    _w_ widen  _]_ next page
	_d_ narrow to defun   ^ ^        _[_ previous page
	_r_ narrow to region  ^ ^        ^ ^
	^ ^                   ^ ^        ^ ^
	"
	("q" nil "cancel")
	("p" narrow-to-page)
	("d" narrow-to-defun)
	("r" narow-to-region)
	("w" widen)
	("]" utz/narrow-page-forward)
	("[" utz/narrow-page-backward))
    #+END_SRC

*** Setup "Quit / Restart" prefix keys

    #+BEGIN_SRC emacs-lisp
      (utz/set-leader-key :infix "q"
	"" '(:ignore t :wk "Quit / Restart")
	"q" '(kill-emacs :wk "Kill Emacs")
	"r" 'restart-emacs :wk "Restart Emacs")
    #+END_SRC

*** Setup "Comments" prefix keys

    #+BEGIN_SRC emacs-lisp
      (utz/set-leader-key :infix "c"
	"" '(:ignore t :wk "Comments")
	"." '(utz/hydra-comment/body :wk "Transient State"))
    #+END_SRC

    And here's the Hydra for the transient state:

    #+BEGIN_SRC emacs-lisp
      (defhydra utz/hydra-comment (:hint nil :exit t)
	"
	^
	^Figlet
	^------^-----------------------
	_r_: Figletify Region
	_R_: Figletify Region Comment
	_i_: Figlet
	_I_: Figlet Comment
	^
	"
	("i" figlet)
	("I" figlet-comment)
	("r" figlet-figletify-region)
	("R" figlet-figletify-region-comment)
	("q" nil "cancel"))
    #+END_SRC

*** Setup "Buffers / Bookmarks" prefix keys

    #+BEGIN_SRC emacs-lisp
      (utz/set-leader-key :infix "b"
	"" '(:ignore t :wk "Buffers / Bookmarks")
	"b" '(helm-buffers-list :wk "Buffers")
	"m" '(helm-bookmarks :wk "Bookmarks")
	"d" '(evil-delete-buffer :wk "Delete Buffer")
	"p" '(evil-prev-buffer :wk "Previous Buffer")
	"n" '(evil-next-buffer :wk "Next Buffer"))
    #+END_SRC

*** Setup "Toggles" prefix keys

    #+BEGIN_SRC emacs-lisp
      (utz/set-leader-key :infix "t"
	"" '(:ignore t :wk "Toggles")
	"f" '(toggle-frame-fullscreen :wk "Full Screen")
	"m" '(toggle-frame-maximized :wk "Maximized"))
    #+END_SRC

*** Setup "Help / Helm" prefix keys

    #+BEGIN_SRC emacs-lisp
      (utz/set-leader-key :infix "h"
	"" '(:ignore t :wk "Help / Helm")
	"f" '(helpful-callable :wk "Helpful Callable")
	"v" '(helpful-variable :wk "Helpful Variable")
	"k" '(helpful-key :wk "Helpful Key")
	"=" '(describe-text-properties :wk "Describe Text Properties")
	"F" '(helpful-function :wk "Helpful Function")
	"c" '(helpful-command :wk "Helpful Command"))

      (utz/set-leader-key :infix "h h"
	"" '(:ignore t :wk "Helm")
	"c" '(helm-colors :wk "Colors"))
    #+END_SRC

*** Setup "Window" prefix keys

    #+BEGIN_SRC emacs-lisp
      (utz/set-leader-key "w" `(,(general-simulate-key "C-w") :wk "Window"))
    #+END_SRC

** `<localleader>` keys

   We begin by creating a definer that we can use for all these mode-based keyboard shortcuts.

*** Org Mode

**** "l" - Links

     #+BEGIN_SRC emacs-lisp
       (utz/set-localleader-key :states '(normal) :keymaps '(org-mode-map)
	 :infix "l"
	 "" '(:ignore t :wk "Links")
	 "o" '(org-open-at-point :wk "Open at Point")
	 "t" '(org-toggle-link-display :wk "Toggle Link Display")
	 "l" '(org-insert-link :wk "Insert Link"))
     #+END_SRC

* Package Config

** Tools

*** Diminish

    Diminish is neat. [[file:./straight/repos/diminish.el/README.md][README]]

    #+BEGIN_SRC emacs-lisp
      (use-package diminish)
    #+END_SRC

*** Delight

  Delight has no README.

    #+BEGIN_SRC emacs-lisp
      (use-package delight)
    #+END_SRC

*** Undo Tree

    Undo Tree has no README.

    #+BEGIN_SRC emacs-lisp
      (use-package undo-tree
	:diminish)
    #+END_SRC

*** Magit

    #+BEGIN_SRC emacs-lisp
      (use-package magit
	:commands (magit-dispatch magit-status))
    #+END_SRC

*** Helpful

    #+BEGIN_SRC emacs-lisp
      (use-package helpful)
    #+END_SRC

*** Which Key

    We sure do love Which Key. [[file:./straight/repos/emacs-which-key/README.org][README]]

    #+BEGIN_SRC emacs-lisp
      (use-package which-key
	:diminish
	:config
	(which-key-mode)
	(which-key-setup-side-window-right-bottom))
    #+END_SRC

*** Helm

    #+BEGIN_SRC emacs-lisp
      (use-package helm
	:diminish
	:init
	(helm-mode 1))
    #+END_SRC

*** Restart Emacs

    Let's make this as easy as possible, eh?

    #+BEGIN_SRC emacs-lisp
      (use-package restart-emacs
	:commands restart-emacs)
    #+END_SRC

*** Flycheck

    #+BEGIN_SRC emacs-lisp
      (use-package flycheck
	:config
	(global-flycheck-mode))
    #+END_SRC

*** Company

    #+BEGIN_SRC emacs-lisp
      (use-package company
	:init
	(add-hook 'after-init-hook 'global-company-mode))
    #+END_SRC

*** Rainbow Mode

    #+BEGIN_SRC emacs-lisp
      (use-package rainbow-mode)
    #+END_SRC

*** Figlet

    #+BEGIN_SRC emacs-lisp
      (use-package figlet
	:general (utz/set-leader-key "c f F" 'figlet-comment
		   "c f f" 'figlet
		   "c f r" 'figlet-figletify-region
		   "c f R" 'figlet-figletify-region))
    #+END_SRC

*** Org

    #+BEGIN_SRC emacs-lisp
      (use-package org
	:custom ((org-startup-with-inline-images t)))
    #+END_SRC

**** Org Bullets

     #+BEGIN_SRC emacs-lisp
       (use-package org-bullets
	 :after org
	 :custom
	 (org-src-tab-acts-natively t)
	 :init
	 (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
     #+END_SRC

**** TOC Org

     #+BEGIN_SRC emacs-lisp
       (use-package toc-org
	 :after org)
     #+END_SRC

*** Treemacs

    #+BEGIN_SRC emacs-lisp
      (use-package treemacs
	:commands (treemacs treemacs-select-window))

      (use-package treemacs-evil
	:after (treemacs evil))

      (use-package treemacs-magit
	:after (treemacs magit))
    #+END_SRC

*** Ranger

    Use [[https://github.com/ralesi/ranger.el][Ranger]] as a file manager, like, a lot. [[file:./straight/repos/ranger.el/README.md][README]]

    #+BEGIN_SRC emacs-lisp
      (use-package ranger
	:commands ranger
        :custom (ranger-override-dired-mode t))
    #+END_SRC

*** YASnippet

    [[file:./straight/repos/yasnippet/README.mdown][README]]

    #+BEGIN_SRC emacs-lisp
      (use-package yasnippet
	:diminish
	:custom
	(yas-snippet-dirs `(,(expand-file-name "snippets/" user-emacs-directory)))
	(yas-verbosity 2)
	:config
	(yas-global-mode 1))
    #+END_SRC

** Languages

*** Markdown

    Using [[https://github.com/jrblevin/markdown-mode][markdown-mode]]. [[file:straight/repos/markdown-mode/README.md][README]]

    #+BEGIN_SRC emacs-lisp
      (use-package markdown-mode
	:custom ((markdown-open-command "~/bin/mark"))
	:mode (("README\\.(md|mdown)\\'" . gfm-mode)
	       ("\\.md\\'" . markdown-mode)
	       ("\\.markdown\\'" . markdown-mode))
	:init (setq markdown-command "multimarkdown"))
    #+END_SRC

*** TypeScript

    Using [[https://github.com/ananthakumaran/tide][Tide]]. [[file:./straight/repos/tide/README.md][README]]

    #+BEGIN_SRC emacs-lisp
      (use-package tide
	:after (typescript-mode company flycheck)
	:hook ((typescript-mode . tide-setup)
	       (typescript-mode . tide-hl-identifier-mode)
	       (before-save . tide-format-before-save)))
    #+END_SRC


*** Emacs Lisp

#+BEGIN_SRC emacs-lisp
(use-package paredit
:commands (enable-paredit-mode))
#+END_SRC
