vim.o.tabstop = 2
vim.o.softtabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.o.relativenumber = true
vim.o.showcmd = true
vim.o.cursorline = true
vim.o.wildmenu = true
vim.o.lazyredraw = true
vim.o.showmatch = true
vim.o.timeout = true -- default, but necessary for vim-which-key
vim.o.timeoutlen = 50
vim.o.incsearch = true
vim.o.hlsearch = true
vim.o.modeline = true
vim.o.foldenable = true
vim.o.foldlevelstart = 10
vim.o.foldnestmax = 10
vim.o.foldmethod = "indent"
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.undofile = true
vim.o.undodir = vim.fn.stdpath('config') .. [[/undo]]
vim.o.autoread = true
vim.o.wrap = false
