[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "git@github.com:tmux-plugins/tpm"
refreshPeriod = "1h"

[".local/share/nu_scripts"]
type = "git-repo"
url = "git@github.com:theutz/nu_scripts"
refreshPeriod = "1h"
