encryption = "gpg"

[gpg]
recipient = "FD235DFD"

[age]
identity = "~/.config/chezmoi/key.txt"
recipient = "age1y5xgp4msrrhylvla0hcm7srsfjeql56p4ugfwsl89wsjs92vkvts3u5xxa"

[git]
autoCommit = false
autoPush = false

[diff]
pager = "delta"
args = ["{{ .Destination }}", "{{ .Target }}"]
exclude = ["scripts"]

[merge]
command = "nvim"
args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

# vim: ft=tmpl.toml
