[".config/zsh/.zprezto"]
type = "git-repo"
url = "https://github.com/theutz/prezto"
refreshPeriod = "1h"
clone.args = ["--recursive"]

[".config/zsh/.zprezto/contrib/zsh-defer"]
type = "git-repo"
url = "https://github.com/romkatv/zsh-defer"
refreshPeriod = "168h"
clone.args = ["--recursive"]
