encryption = "age"

[age]
	identity = "~/.config/chezmoi/key.txt"
	recipient = "age1y5xgp4msrrhylvla0hcm7srsfjeql56p4ugfwsl89wsjs92vkvts3u5xxa"

[git]
  autoCommit = false
  autoPush = false

[merge]
  command = "nvim"
  args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

[diff]
  pager = "diff-so-fancy"
