[".zprezto"]
type = "git-repo"
url = "https://github.com/theutz/prezto"
refreshPeriod = "1h"

[".zprezto".clone]
args = ["--recursive"]

[".zprezto-contrib"]
type = "git-repo"
url = "https://github.com/theutz/prezto-contrib"
refreshPeriod = "1h"

[".config/nvim"]
type = "git-repo"
url = "https://github.com/theutz/nvim"
refreshPeriod = "1h"

# vim: ft=tmpl.toml
