[".config/zsh/prezto"]
type = "git-repo"
url = "https://github.com/theutz/prezto"
refreshPeriod = "1h"
clone.args = ["--recursive"]

[".config/zsh/prezto/contrib/zsh-defer"]
type = "git-repo"
url = "https://github.com/romkatv/zsh-defer"
refreshPeriod = "168h"
clone.args = ["--recursive"]

[".config/nvim"]
type = "git-repo"
url = "https://github.com/theutz/nvim"
refreshPeriod = "1h"
