[".config/zsh/zprezto"]
type = "git-repo"
url = "https://github.com/sorin-ionescu/prezto"
refreshPeriod = "168h"

[".config/zsh/zprezto".clone]
args = ["--recursive"]

[".config/kitty/themes/kanagawa.conf"]
type = "file"
url = "https://raw.githubusercontent.com/rebelot/kanagawa.nvim/master/extras/kanagawa.conf"
refreshPeriod = "168h"

[".config/kitty/themes/kanagawa_light.conf"]
type = "file"
url = "https://raw.githubusercontent.com/rebelot/kanagawa.nvim/master/extras/kanagawa_light.conf"
refreshPeriod = "168h"

[".config/kitty/themes/kanagawa_dragon.conf"]
type = "file"
url = "https://raw.githubusercontent.com/rebelot/kanagawa.nvim/master/extras/kanagawa_dragon.conf"
refreshPeriod = "168h"

[".config/alacritty/themes"]
type = "archive"
url = "https://github.com/alacritty/alacritty-theme/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
include = ["*/themes/**", "*.yaml"]
