# This tmux statusbar config was created by tmuxline.vim
# on Sun, 11 Jul 2021

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=#30365F,bg=#686f9a"
set -g status-right-style "none"
set -g pane-active-border-style "fg=#30365F"
set -g status-style "none,bg=#686f9a"
set -g message-style "fg=#30365F,bg=#686f9a"
set -g pane-border-style "fg=#686f9a"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#30365F,bg=#686f9a"
set -g status-left "#[fg=#000000,bg=#30365F] #S #[fg=#30365F,bg=#686f9a,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#686f9a,bg=#686f9a,nobold,nounderscore,noitalics]#[fg=#30365F,bg=#686f9a] %Y-%m-%d  %H:%M #[fg=#30365F,bg=#686f9a,nobold,nounderscore,noitalics]#[fg=#000000,bg=#30365F] #h "
setw -g window-status-format "#[fg=#30365F,bg=#686f9a] #I #[fg=#30365F,bg=#686f9a] #W "
setw -g window-status-current-format "#[fg=#686f9a,bg=#686f9a,nobold,nounderscore,noitalics]#[fg=#30365F,bg=#686f9a] #I #[fg=#30365F,bg=#686f9a] #W #[fg=#686f9a,bg=#686f9a,nobold,nounderscore,noitalics]"
