# This tmux statusbar config was created by tmuxline.vim
# on Sun, 13 Jun 2021

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=#809980,bg=#5e6e5e"
set -g status-right-style "none"
set -g pane-active-border-style "fg=#809980"
set -g status-style "none,bg=#242924"
set -g message-style "fg=#809980,bg=#5e6e5e"
set -g pane-border-style "fg=#5e6e5e"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#809980,bg=#242924"
set -g status-left "#[fg=#242924,bg=#809980] #S #[fg=#809980,bg=#242924,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#5e6e5e,bg=#242924,nobold,nounderscore,noitalics]#[fg=#809980,bg=#5e6e5e] %Y-%m-%d  %H:%M #[fg=#809980,bg=#5e6e5e,nobold,nounderscore,noitalics]#[fg=#242924,bg=#809980] #h "
setw -g window-status-format "#[fg=#809980,bg=#242924] #I #[fg=#809980,bg=#242924] #W "
setw -g window-status-current-format "#[fg=#242924,bg=#5e6e5e,nobold,nounderscore,noitalics]#[fg=#809980,bg=#5e6e5e] #I #[fg=#809980,bg=#5e6e5e] #W #[fg=#5e6e5e,bg=#242924,nobold,nounderscore,noitalics]"
