# List Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-fpp'
set -g @plugin 'tmux-plugins/tmux-urlview'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'schasse/tmux-jump'
set -g @plugin 'sainnhe/tmux-fzf'

# Set Options
set -g @themepack 'powerline/default/blue'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'
set -g mouse on

# Make sure spaceduck theme works correctly with vim
set -g terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

#~~~~~~~~~~~~~~~~~~
# PERSONAL SETTINGS
#~~~~~~~~~~~~~~~~~~

#
# Settings
#
setw -g mode-keys vi
set -g default-shell "/usr/local/bin/zsh"

#
# Keybindings
#
bind-key M-g popup -w 90% -h 90% -E "[ -d .git ] && lazygit || yadm enter lazygit"

# Popup Edits
bind-key M-v popup -w 120 -h 90% -E "cd ~/.config/nvim && nvim -S"
bind-key M-t popup -w 120 -h 90% -E "nvim ~/.tmux.conf"\; source-file ~/.tmux.conf\; display-message '~/.tmux.conf reloaded!'
bind-key M-z popup -w 120 -h 90% -E "cd ~/.zprezto/runcoms && nvim -S"
bind-key M-y popup -w 120 -h 90% -E "nvim ~/.config/yadm"
bind-key M-f popup -w 120 -h 90% -E "nvim ~/.finicky.js"
bind-key M-h popup -w 120 -h 90% -E "nvim ~/.hammerspoon/init.lua"
bind-key M-Space popup -w 120 -h 90% -E
bind-key M-m command-prompt -p "Search man:" 'popup -E "man %%"'

# Tmux FZF
TMUX_FZF_LAUNCH_KEY="C-f"
bind-key C-p run-shell -b "$TMUX_PLUGIN_MANAGER_PATH/tmux-fzf/scripts/pane.sh switch"

# Other
bind-key r source-file ~/.tmux.conf \; display-message '~/.tmux.conf reloaded!'
bind-key C-l send-keys C-l
bind-key C-h send-keys C-h

# Generated from Tmuxline.vim
source "$HOME/.tmux-theme.conf"
