alias cm = ^chezmoi
alias cma = cm add
alias cmap = cm apply
alias cmd = cm diff
alias cme = cm edit
alias cmm = cm merge
alias cmma = cm merge-all
alias cmra = cm re-add
alias cmrm = cm remove
alias cms = cm status
alias cmx = cm forget
