[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "git@github.com:tmux-plugins/tpm"
refreshPeriod = "24h"
exact = false

[".zprezto"]
type = "git-repo"
url = "git@github.com:sorin-ionescu/prezto"
refreshPeriod = "24h"
exact = false
clone.args = ['--recursive']
pull.args = ['--recurse-submodules']

[".local/share/cheat/cheatsheets/community"]
type = "git-repo"
url = "git@github.com:cheat/cheatsheets"
refreshPeriod = "24h"
exact = false
