[".zprezto"]
type = "git-repo"
url = "git@github.com:sorin-ionescu/prezto"
refreshPeriod = "24h"
exact = false
clone.args = ['--recursive']
pull.args = ['--recurse-submodules']

[".local/share/cheat/cheatsheets/community"]
type = "git-repo"
url = "git@github.com:cheat/cheatsheets"
refreshPeriod = "24h"
exact = false

[".hammerspoon"]
type = "git-repo"
url = "git@github.com:theutz/.hammerspoon"
refreshPeriod = "168h"
exact = false
stripComponents = 1

[".config/nvim"]
type = "git-repo"
url = "git@github.com:theutz/nvim"
refreshPeriod = "168h"
exact = false

[".config/fish"]
type = "git-repo"
url = "git@github.com:theutz/fish"
refreshPeriod = "168h"
exact = false

[".config/sketchybar"]
type = "git-repo"
url = "git@github.com:theutz/sketchybar"
refreshPeriod = "168h"
exact = false
