# List Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-fpp'
set -g @plugin 'tmux-plugins/tmux-urlview'

# Set Options
set -g @themepack 'powerline/default/blue'
set -g @continuum-restore 'on'
set -g mouse on

# Make sure spaceduck theme works correctly with vim
set -g terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Personal settings
setw -g mode-keys vi
set -g default-shell "/usr/local/bin/zsh"

# Personal Keybindings
bind-key g split-window -e TERM=screen-256color -l 70% lazygit
bind-key r source-file ~/.tmux.conf \; display-message '~/.tmux.conf reloaded'
bind-key R split-window -h 'nvim ~/.tmux.conf'
