abbr -a -- brewi 'brew install'
abbr -a -- brewin 'brew info'
abbr -a -- brewl 'brew list'
abbr -a -- brews 'brew search'
abbr -a -- brewx 'brew uninstall'
abbr -a -- c chezmoi
abbr -a -- caski 'brew install --cask'
abbr -a -- caskx 'brew uninstall --cask'
abbr -a -- cat bat
abbr -a -- cma 'chezmoi add'
abbr -a -- cmad 'chezmoi add-deleted'
abbr -a -- cmap 'chezmoi apply'
abbr -a -- cmcd 'chezmoi cd'
abbr -a -- cmd 'chezmoi diff'
abbr -a -- cme 'chezmoi edit'
abbr -a -- cmea 'chezmoi edit --apply'
abbr -a -- cmew 'chezmoi edit --watch'
abbr -a -- cmfm 'chezmoi forget-missing'
abbr -a -- cmfzfa 'cmfzf | xargs chezmoi add'
abbr -a -- cmma 'chezmoi merge-all'
abbr -a -- cmra 'chezmoi re-add'
abbr -a -- cmS 'chezmoi status'
abbr -a -- cms 'chezmoi status-all'
abbr -a -- cmsa 'chezmoi status-all'
abbr -a -- cmsw 'chezmoi status-watch'
abbr -a -- gc 'git commit'
abbr -a -- gca 'git add -A; and git commit'
abbr -a -- gcap 'git add -A; and git commit; and git pull; and git push'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gf 'git fetch'
abbr -a -- gfm 'git pull'
abbr -a -- gia 'git add'
abbr -a -- giaa 'git add -A'
abbr -a -- gid 'git diff --no-ext-diff'
abbr -a -- gl 'git log'
abbr -a -- gpp 'git pull; and git push'
abbr -a -- gwd 'git diff --cached --no-ext-diff'
abbr -a -- gws 'git status --short'
abbr -a -- gwS 'git status'
abbr -a -- hsrl 'hs -c "hs.reload()"'
abbr -a -- l ls
abbr -a -- lg lazygit
abbr -a -- md 'mkdir -p'
abbr -a -- mr 'mise run'
abbr -a -- mt 'mise tasks'
abbr -a -- mta 'mise tasks add'
abbr -a -- mtaf 'mise tasks add --file'
abbr -a -- mtx 'mise tasks -x'
abbr -a -- mu 'mise use'
abbr -a -- mug 'mise use -g'
abbr -a -- newt 'wezterm cli spawn'
abbr -a -- neww 'wezterm cli spawn --new-window'
abbr -a -- n 'neovide --no-fork'
abbr -a -- nf 'neovide --fork'
abbr -a -- pbc pbcopy
abbr -a -- pbp pbpaste
abbr -a -- service 'brew services'
abbr -a -- wsh 'wezterm ssh'
abbr -a -- wz wezterm
abbr -a -- wzc 'wezterm cli'
abbr -a -- wzcl 'wezterm cli list'
abbr -a -- wzct 'wezterm cli spawn'
abbr -a -- wzcw 'wezterm cli spawn --new-window'
abbr -a -- m mise
abbr -a -- zj zellij
abbr -a -- zjls 'zellij ls'
abbr -a -- bb 'brew bundle'
abbr -a -- bbg 'brew bundle --global'
abbr -a -- bbga 'brew bundle --global add'
abbr -a -- ps procs
abbr -a -- p pueue
abbr -a -- idea eureka
abbr -a -- bbgx 'brew bundle --global remove'
abbr -a -- a aichat
abbr -a -- ae 'aichat -e'
abbr -a -- cmam 'chezmoi add-missing'
abbr -a -- cmls 'chezmoi managed'
abbr -a -- we wezterm
abbr -a -- wels 'wezterm cli list'
