#!/usr/bin/env zsh

set -euo pipefail

interval=6
args=()
while [[ $# -gt 0 ]]; do
  case "$1" in
  --interval | -i)
    interval="$2"
    shift 2
    ;;
  *)
    args=("$1")
    ;;
  esac
done
set -- "${args[@]}"

while :; do
  tmux popup -EE jrnl || true
  gum spin --title="Waiting for $interval minutes..." -- sleep "$((60 * $interval))"
done
