#!/usr/bin/env zsh

set -euo pipefail

while :; do
  cms="$(chezmoi status-all)"
  d="$(date +'%H:%M:%S' | gum style --faint --italic)"
  msg="$(gum join --vertical --align right "$cms" "$d")"
  clear
  echo "$msg"
  sleep 5
done
