#!/usr/bin/env zsh
set -euo pipefail

setopt monitor

tmpdir="$(mktemp -d -t cms)"
cms_path="${tmpdir}/cms"
gws_path="${tmpdir}/gws"

# TRAPEXIT() {
#   if [[ -d $tmpdir ]]; then
#     rm -r $tmpdir
#   fi
# }

export BORDER="rounded"
export PADDING="0 2"
export MARGIN="1 0 0 2"

mkfifo $cms_path $gws_path

chezmoi status > $cms_path &!
chezmoi git -- -c color.status=always status --short > $gws_path &!

cms="$(cat $cms_path)"
gws="$(cat $gws_path)"

if [[ -n "$cms" ]]; then
  cms="
  $(gum format -- '## Chezmoi Status')
  $(gum style -- "$cms")
  "
fi

if [[ -n "$gws" ]]; then
  gws="
  $(gum format -- '## Git Status')
  $(gum style -- "$gws")
  "
fi

cols="$(tput cols)"
flags=()
if [[ $cols -gt 100 ]]; then
  flags+=(
    "--horizontal"
    "--align middle"
  )
else
  flags+=(
    "--vertical"
    "--align left"
  )
fi

gum join "${(z)flags[@]}" "$cms" "$gws"
