#!/usr/bin/env bash

set -euxo pipefail

positional=()
workspace=""

while [[ $# -gt 0 ]]; do
  case "$1" in
  --workspace | -w)
    workspace="$2"
    shift 2
    ;;
  --)
    shift
    positional+=("$@")
    break
    ;;
  *)
    positional+=("$1")
    shift
    ;;
  esac
done

set -- "${positional[@]}"

wezterm \
  --config enable_tab_bar=false \
  --config window_close_confirmation=\'NeverPrompt\' \
  --config quit_when_all_windows_are_closed=true \
  start \
  ${workspace:+--workspace="$workspace"} \
  -- \
  "$@" >/dev/null 2>&1 &
disown
