#!/usr/bin/env -S mise x uv -- uv run --script
# /// script
# ///

import subprocess
import re
import os

status = subprocess.run(["chezmoi", "status"], capture_output=True, text=True)
lines = status.stdout.splitlines()

files = []

for line in lines:
    m = re.match(r"^(..) (.*)$", line)

    if m is None:
        raise Exception("Didn't work")

    if m.group(1) == " D":
        files.append(f"{os.environ['HOME']}/{m.group(2)}")

cmd = ["chezmoi", "add"]
cmd.extend(files)
subprocess.run(cmd)

# vim: ft=python
