#!/usr/bin/env -S mise x fzf ripgrep -- zsh
# vim: ft=zsh

files="$(chezmoi status |
  rg '^ D' |
  fzf --multi \
      --query="${1:-}" \
      --select-1 \
      --bind='ctrl-a:toggle-all' \
      --prompt='Add deleted: ' \
      --nth='2..' \
      --accept-nth='~/{2}' \
      --preview='chezmoi diff ~/{2}'
)"

if [[ -n "$files" ]]; then
  chezmoi add "${(f)files[@]}"
fi
