#!/usr/bin/env zsh

export BORDER="rounded"
export PADDING="0 2"
export MARGIN="1 0 0 2"

gum format -- '# Chezmoi Status'
gum style -- "$(chezmoi status)"
gum format -- '# Chezmoi Git Status'
gum style -- "$(chezmoi git -- -c color.status=always status)"
