#!/usr/bin/env -S mise x python@latest uv@latest -- uv run --script
# /// script
# dependencies = []
# ///
# vim: ft=python

import os
import subprocess
import sys


def open_in_editor(*files):
    editor = os.getenv("VISUAL") or os.getenv("EDITOR")
    assert editor
    editor = editor.split()
    editor = [word.replace(" ", "") for word in editor]

    if editor:
        try:
            subprocess.run(editor + list(files))
        except FileNotFoundError:
            print(
                f"Editor '{editor}' not found. Please ensure it is installed and in your PATH"
            )
    else:
        print("No VISUAL or EDITOR environment variable is set.")
        sys.exit(1)


if __name__ == "__main__":
    open_in_editor(*sys.argv[1:])
