#!/usr/bin/env zsh

set -euo pipefail

SCRIPT_NAME="${0:t}"

log() {
  gum log --prefix="$SCRIPT_NAME" --structured "$@"
}

debug() {
  if [[ -v DEBUG && $DEBUG == true ]]; then
    log -l debug "$@"
  fi
}

DEBUG=false
export DEBUG

clear_screen=true
interval=6
pesky_dir="${XDG_DATA_HOME:-$HOME/.local/share}/pesky"
timesheet="$pesky_dir/timesheet.csv"

args=()
while [[ $# -gt 0 ]]; do
  debug "parsing arg" "'$1'" "${2:-''}"
  case "$1" in
  --verbose | -v)
    DEBUG=true
    export DEBUG
    clear_screen=false
    debug -- "parsing arg" "'$1'"
    shift 1
    ;;
  --timesheet | -t)
    timesheet="$2"
    shift 2
    ;;
  --interval | -i)
    debug -- "parsed '$1' as $2"
    interval="$2"
    shift 2
    ;;
  *)
    args=("$1")
    ;;
  esac
done
set -- "${args[@]}"

for v in pesky_dir timesheet interval clear_screen; do
  debug "setting" "$v" "${(P)v}"
done

while :; do
  minutes="$interval"
  while [[ "$minutes" -gt 0 ]]; do
    debug remaining minutes "$minutes"
    gum spin --spinner moon \
      --title="Waiting for $minutes more minutes..." \
      -- \
      sleep 60
    debug "subtracting 1 minute"
    minutes="$((minutes - 1))"
  done
  noti -t "$SCRIPT_NAME" -m "time to update"
done
