#!/usr/bin/env zsh

set -euo pipefail

while :; do
  header="$(gum format -- "# Chezmoi")"
  d="$(date +'%H:%M:%S' | gum style --padding="0 3" --faint --italic)"
  cms="$(chezmoi status-all)"

  if [[ -n "$cms" ]]; then
    msg="$(gum join --vertical --align left "$header" "$cms" "$d")"
  else
    msg=(
      "$header"
      "$(gum format -- "## Everything up to date")"
    )
  fi

  clear
  echo "$msg"
  sleep 3
done
