#!/usr/bin/env bash

set -euo pipefail

function choose() {
  fzf --multi \
    --exit-0 \
    --bind 'ctrl-a:toggle-all' \
    --bind 'start:select-all' \
    --prompt "$1" \
    --accept-nth "$HOME/{2}" \
    --nth '2..' \
    --print0 \
    --preview "chezmoi diff $HOME/{2}"
}

function main() {
  chezmoi status --include templates |
    rg '^MM' |
    choose "Merge templates: " |
    xargs --null \
      --no-run-if-empty \
      pueue add -- chezmoi merge || true

  gum spin --title "Merging..." -- pueue wait

  chezmoi status --exclude templates |
    rg '^MM' |
    choose "Re-add: " |
    xargs --null \
      --no-run-if-empty \
      pueue add -- chezmoi re-add || true
  gum spin --title "Re-adding..." -- pueue wait

  chezmoi status --exclude templates |
    rg '^DA' |
    choose "Forget missing: " |
    xargs --null \
      --no-run-if-empty \
      pueue add -- chezmoi forget --force || true

  gum spin "Forgetting..." -- pueue wait

  chezmoi status --exclude templates |
    rg '^ D' |
    choose "Add deleted: " |
    xargs --null \
      --no-run-if-empty \
      pueue add -- chezmoi add || true

  gum spin --title "Adding..." -- pueue wait
}

main
