#!/usr/bin/env -S mise x python@latest uv@latest -- uv run --script
# /// script
#  dependencies = ["requests", "beautifulsoup4", "rich"]
# ///

import argparse
import requests
from bs4 import BeautifulSoup
import time
import os
import datetime
from rich import print
from rich.padding import Padding

def parse_arguments():
    parser = argparse.ArgumentParser(description='Check DNS leak information')
    parser.add_argument('--watch', '-w', action='store_true', help='Watch mode - continuously check')
    parser.add_argument('--interval', '-i', type=int, default=60, help='Interval between checks in seconds (default: 60)')
    parser.add_argument('--clear', '-c', action='store_true', help='Clear screen before each output')
    return parser.parse_args()

def run(clear=False):
    response = requests.get('https://dnsleaktest.com')
    soup = BeautifulSoup(response.text, 'html.parser')
    res = soup.select_one('.welcome').get_text(strip=False)
    current_time = datetime.datetime.now().strftime('%H:%M:%S')

    out = Padding(f'[bold]Current location[/bold]\n\n{res}\n{current_time}', (1, 4))

    if clear:
        os.system('clear')

    print(out)

def main():
    args = parse_arguments()

    if args.watch:
        while True:
            run(args.clear)
            time.sleep(args.interval)
    else:
        run(args.clear)

if __name__ == "__main__":
    main()
