#!/usr/bin/env zsh

set -euo pipefail

while :; do
  cms="$(chezmoi status-all)"
  if [[ -n "$cms" ]]; then
    d="$(date +'%H:%M:%S' | gum style --faint --italic)"
    msg="$(gum join --vertical --align right "$cms" "$d")"
  else
    msg="$(gum format -- "# Everything up to date")"
  fi
  clear
  echo "$msg"
  sleep 5
done
