#!/usr/bin/env zsh

set -euo pipefail

SCRIPT_NAME="${0:t}"

log() {
  gum log --prefix="$SCRIPT_NAME" "$@"
}

debug() {
  if [[ -v DEBUG && $DEBUG == true ]]; then
    log -l debug "$@"
  fi
}

DEBUG=false
export DEBUG

clear_screen=true
interval=6

args=()
while [[ $# -gt 0 ]]; do
  case "$1" in
  --verbose | -v)
    DEBUG=true
    export DEBUG
    clear_screen=false
    debug -- "parsed '$1'"
    shift 1
    ;;
  --interval | -i)
    debug -- "parsed '$1' as $2"
    interval="$2"
    shift 2
    ;;
  *)
    args=("$1")
    ;;
  esac
done
set -- "${args[@]}"

while :; do
  debug creating empty jrnl entry
  jrnl EMPTY

  debug popping up jrnl
  tmux popup -EE jrnl -today --edit

  if [[ "$clear_screen" == true ]]; then
    debug clearing screen
    clear
  else
    debug "not clearing screen"
  fi

  debug "listing today's entries"
  jrnl -today

  debug "initial minutes to wait $interval"
  minutes="$interval"
  while [[ "$minutes" -gt 0 ]]; do
    debug "minutes left to wait $minutes"
    gum spin --spinner moon \
      --title="Waiting for $minutes more minutes..." \
      -- \
      sleep 60
    debug "subtracting one minute"
    minutes="$((minutes - 1))"
  done
  debug "notifying of new chances"
  noti -t pesky -m "time to update"
done
