#!/usr/bin/env -S mise x fzf ripgrep -- zsh
# vim: ft=zsh

files="$(
  chezmoi status |
    rg '^DA' |
    fzf --multi \
        --bind='ctrl-a:toggle-all' \
        --prompt='Forget missing: ' \
        --nth='2..' \
        --accept-nth='~/{2}' \
        --preview='chezmoi diff ~/{2}'
)"

if [[ -n "$files" ]]; then
  chezmoi forget "${(f)files[@]}"
fi
