#!/usr/bin/env zsh

# Save scheme as a string
scheme="$(dark-notify -e | tr -d '\n')"

# Reload sketchybar
sketchybar --reload

# Reload tmux
tmux source-file "${XDG_CONFIG_HOME:-${HOME/.config}}"/tmux/tmux.conf

# Update Lazygit Paging
yq -i \
  ".git.paging.pager = \"delta --$scheme --paging=never\"" \
  $XDG_CONFIG_HOME/lazygit/config.yml

# Reload qutebrowser config
qutebrowser :config-source
