[[snippets]]
  description = "Update global Brewfile"
  command = "brew bundle --global dump --all --describe --force"
  output = ""

[[snippets]]
  description = "Create a private git repo from the current directory"
  command = "gh repo create -s . --private"
  output = ""
