customCommands:
  - key: b
    context: files
    command: nu -c "git-commit-message-ai"
    description: generate commit message with ai
    output: terminal
disableStartupPopups: true
git:
  commit:
    signOff: true
  paging:
    useExternalDiffGitConfig: true
  parseEmoji: true
  overrideGpg: true
gui:
  border: rounded
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  showBottomLine: false
  showCommandLog: true
  showRandomTip: false
notARepository: skip
promptToReturnFromSubprocess: false
