customCommands:
  - key: b
    context: files
    command: |-
      git diff --cached |
      mods -R commit |
      sd '^```(.*?)```$' '$1' |
      git commit --file -
    description: generate commit message with ai
    output: terminal
disableStartupPopups: true
git:
  commit:
    signOff: true
  paging:
    useExternalDiffGitConfig: false
  parseEmoji: true
  overrideGpg: true
gui:
  border: rounded
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  showBottomLine: false
  showCommandLog: true
  showRandomTip: false
notARepository: skip
promptToReturnFromSubprocess: false
