export alias tx    = tmux
export alias txa   = tmux attach
export alias txls  = tmux ls+
export alias txp   = tmuxp
export alias txpe  = tmuxp edit+
export alias txpl  = tmuxp load+
export alias txpls = tmuxp ls+
export alias txpp  = tmuxp pick
export alias txps  = tmuxp switch
export alias txx   = tmux kill-session+
