#!/usr/bin/env zsh

cmd="$(where brew | grep homebrew)"

function update-global-brewfile() {
  $cmd bundle dump --global --desc --force --cleanup \
    && chezmoi add "$(chezmoi target-path)/.Brewfile"
}

case "$1" in
  install|uninstall)
    $cmd "$@" && update-global-brewfile
    ;;
  *)
    $cmd "$@"
    ;;
esac

exit $?
