#!/usr/bin/env zsh

set -euo pipefail

local readd=()
local destroy=()
local apply=()

while read -r stat file; do
  case $stat in
    MM)
      gum log -l info --prefix "re-add" " $file"
      readd+="$file"
      ;;
    DA)
      gum log -l warn --prefix destroy "$file"
      destroy+="$file"
      ;;
    D)
      gum log -l warn --prefix apply "  $file"
      apply+="$file"
      ;;
    "")
      gum log -l info "No files to sync"
      ;;
    *)
      gum log -l error --prefix "ERROR" "unknown status: $stat"
      gum log --prefix "$file"
      exit 1
      ;;
  esac
done <<< $(chezmoi status)

if
  (
    (( $#readd )) ||
      (( $#destroy )) ||
      (($#apply))
  ) && gum confirm "Proceed"
then
  (( $#readd )) && chezmoi re-add "${readd[@]}"
  (( $#destroy )) && chezmoi destroy "${destroy[@]}"
  (( $#apply )) && chezmoi apply "${apply[@]}"
fi

chezmoi source-path | read src
cat $src/.chezmoiexternal |
  yj -t |
  jq -r 'keys[] | @sh' |
  while read -r repo; do
    if [[ -n "$(git -C $repo status -s)" ]]; then
      lazygit -p $repo
    fi
  done
