#!/usr/bin/env zsh

if [[ -x artisan && -x please ]]; then
  php please $@
elif [[ -x artisan ]]; then
  php please $@
elif [[ -x vendor/bin/wp ]]; then
  vendor/bin/wp $@
elif [[ -x craft ]]; then
  php craft $@
else
  print "No commands found"
  return 1
fi
