#!/usr/bin/env zsh

set -euo pipefail

trap 'rm -f "$new" "$old"' EXIT
old="$(mktemp)"
new="$(mktemp)"
brewfile="$HOME/.Brewfile"

cp -f $brewfile $old

brew bundle --file="$new" dump --force --no-upgrade --no-restart
nvim -d "$new" "$brewfile" "$old" -c 'wincmd l' -c 'norm gg]c'
brew bundle --global --zap --cleanup --no-upgrade
