#!/usr/bin/env zsh

set -euo pipefail

# Get the session name
if [[ -n "$@" ]]; then
  session="$@"
else
  session="$(tmuxp ls | gum filter --fuzzy)"
fi

# Load the session if it isn't already
if ! tmux has-session -t "$session" &>/dev/null; then
  gum spin -- tmuxp load -d "$session"
fi

tmux attach-session -t "$session" &>/dev/null \
  || tmux switch-client -t "$session" &>/dev/null
