#!/usr/bin/env zsh

set -euo pipefail

files=$(chezmoi managed -i files,symlinks | sed 's/.*/"&"/')

for file in $files; do
  rm $file || true
done

dirs=$(chezmoi managed -i dirs | sed 's/.*/"&"/')
for dir in $dirs; do
  rmdir $dir || true
done

chezmoi purge --force
