#!/usr/bin/env zsh

export LAZYGIT_NEW_DIR_FILE="${XDG_STATE_HOME}/lazygit/newdir"

lazygit "$@"

if [[ -f $LAZYGIT_NEW_DIR_FILE ]]; then
  cd "$(cat $LAZYGIT_NEW_DIR_FILE)"
  rm -f $LAZYGIT_NEW_DIR_FILE > /dev/null
fi
