#!/usr/bin/env zsh

set -euo pipefail

if [[ -n "$argv" && -n "$argv[1]" ]]; then
  session="$argv[1]"
elif sessions="$(tmux ls 2>/dev/null | cut -d ':' -f1)"; then
  session="$(echo $sessions | gum filter)"
else
  session="$(tmuxp ls | gum filter)"
  tmuxp load -d "$session"
fi
tmux attach-session -t "$session" &>/dev/null || tmux switch-client -t "$session" &>/dev/null
