#!/usr/bin/env zsh

set -euo pipefail

while :; do
  header="$(gum format -- "# Chezmoi")"
  msg=(
    "$header"
  )
  d="$(date +'%H:%M:%S' | gum style --padding="0 3" --faint --italic)"
  cms="$(chezmoi status-all)"

  if [[ -n "$cms" ]]; then
    msg+=(
      "$(gum join --vertical --align left "$cms" "$d")"
    )
  else
    msg+=(
      "$(gum style --faint --italic --padding="2 3" -- "Everything up to date")"
      "$d"
    )
  fi

  msg="$(gum join --vertical "${msg[@]}")"
  clear
  echo $msg
  sleep 2
done
