#!/usr/bin/env zsh -euo pipefail

local readd=()
local destroy=()

while read -r stat file; do
  case $stat in
    MM)
      gum log -l info --prefix "re-add" "$file"
      readd+=$file
      ;;
    DA)
      gum log -l warn --prefix "destroy" "$file"
      destroy+=$file
      ;;
    *)
      gum log -l error --prefix "ERROR" "unknown status: $stat"
      gum log --prefix "$file"
      ;;
  esac
done <<< $(chezmoi status)

if
  ((( $#readd )) || (( $#destroy ))) &&
  gum confirm "Proceed"
then
  if (( $#readd )); then
    chezmoi re-add "${readd[@]}"
  fi
  if (( $#destroy )): then
    chezmoi destroy "${destroy[@]}"
  fi
fi

