#!/usr/bin/env zsh

set -euo pipefail

stat="$(tailscale status | sed -e '/^#/d' -e '/^$/d')"
gum format -- "# Tailscale Status

$stat"

location="$(gum spin --title "Finding current location..." -- dnsleaktest)"
echo $location
echo

tailscale exit-node list |
  sed -e '/^#/d' -e '/^$/d' |
  fzf --header-lines=1 |
  awk '{ print $2 }' |
  xargs tailscale set --exit-node

location="$(gum spin --title "Testing new location..." --show-output -- zsh -c "sleep 1 && dnsleaktest")"
tput cuu1
echo $location
