frame = "transparent"
maximized = false
title-hidden = false

[font]
normal = { family = "MartianMono Nerd Font Propo", style = "Regular" }
bold = { family = "MartianMono Nerd Font Propo", style = "Medium" }
size = 16
