frame = "transparent"
maximized = false
title-hidden = false

[font]
normal = { family = "{{ .fonts.mono.family }}", style = "Regular" }
bold = { family = "{{ .fonts.mono.family }}", style = "Medium" }
size = {{ .fonts.mono.size }}
