#!/usr/bin/env zsh
#set -euo pipefail

# Setup Options
yabai -m config layout float
# yabai -m config window_placement first_child
# yabai -m config auto_balance off
# yabai -m config focus_follows_mouse off
# yabai -m config mouse_follows_focus on
# yabai -m config window_opacity on
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 1.0
# yabai -m config window_shadow on
yabai -m config window_topmost on

# Setup Gaps
pad=10

for dir in top left right bottom
do
  yabai -m config "${dir}_padding" $pad
done

yabai -m config window_gap $pad

# Rules
declare -A grids
grids=(
  [fullscreen]="1:1:1:1:1:1"
)

# Automatically make some apps fullscreen
for app in \
  "^Finder$"\
  "^Alfred"
do
  yabai -m rule --add app!="${app}" \
    grid="${grids[fullscreen]}"
  yabai -m signal --add event="application_activated" \
    app!="$app"\
    action="$(cat << EOF
      yabai -m query --windows \
      | jq --arg processId "\${YABAI_PROCESS_ID}" \
          'map(select(.pid == (\$processId | tonumber) and .focused == 1))[0].id' \
      | xargs -I _ yabai -m window _ --grid ${grids[fullscreen]}
EOF
  )"
done

# Resize some apps differently
yabai -m rule --add app="^System Preferences$" \
  sticky=on \
  grid=20:20:6:4:0:0
