#!/usr/bin/env bash
set -euo pipefail

# Load Yabai Scripting Additions
#sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Setup Options
yabai -m config layout bsp
yabai -m config window_placement first_child
yabai -m config auto_balance on
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.85
yabai -m config window_shadow off 
yabai -m config window_topmost on

# Setup appearance
pad=10

for dir in top left right
do
  yabai -m config "${dir}_padding" $pad
done

yabai -m config window_gap $pad
yabai -m config external_bar all:0:$(($pad * 5))

# Setup Exceptions
for app in "^Mate Translate" "^Bartender" "^Streaks", "^Paletro"
do
  yabai -m rule --add app="$app" manage=off
done
yabai -m rule --add app="^System Preferences$" manage=off sticky=on grid=20:20:6:4:0:0

