theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
shell = [
    "nu",
    "-c",
]
cursorline = true
cursorcolumn = true
rulers = [120]
bufferline = "always"
text-width = 120

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true

[keys.insert] 
"C-/" = ":sh zellij action new-pane --direction down"

[keys.normal]
"C-/" = ":sh zellij action new-pane --direction down"
X = "extend_line_above"

[keys.normal.space]
l = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all",
]
q = ":write-quit-all"
