theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
shell = [
    "nu",
    "-c",
]
cursorline = true
cursorcolumn = true
rulers = [120]
bufferline = "always"
text-width = 120

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true

[keys.normal]
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all",
]

space.q = ":write-quit-all"
