tap "d12frosted/emacs-plus"
tap "denisidoro/tools"
tap "federico-terzi/espanso"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
tap "rigellute/tap"
tap "universal-ctags/universal-ctags"
tap "wtfutil/wtfutil"
cask "xquartz"
brew "asciiquarium"
brew "bat"
brew "bfg"
brew "broot"
brew "python", link: false
brew "ccat"
brew "cmake"
brew "cmatrix"
brew "coreutils"
brew "cowsay"
brew "ddgr"
brew "dialog"
brew "diff-so-fancy"
brew "direnv"
brew "duti"
brew "editorconfig"
brew "fasd"
brew "fd"
brew "tesseract"
brew "ffmpeg"
brew "figlet"
brew "fortune"
brew "fpp"
brew "fzf"
brew "gawk"
brew "gdrive"
brew "gist"
brew "git"
brew "git-flow-avh"
brew "git-lfs"
brew "git-quick-stats"
brew "git-secrets"
brew "gitleaks"
brew "global"
brew "go"
brew "grip"
brew "htop"
brew "hub"
brew "imagemagick"
brew "ispell"
brew "jq"
brew "lolcat"
brew "lsd"
brew "make"
brew "mas"
brew "mdcat"
brew "n"
brew "neovim"
brew "noti"
brew "onefetch"
brew "openvpn", restart_service: true
brew "ossp-uuid"
brew "pandoc"
brew "pkg-config"
brew "png2ico"
brew "poppler"
brew "ripgrep"
brew "rust"
brew "shellcheck"
brew "shpotify"
brew "speedtest-cli"
brew "stow"
brew "surfraw"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "toilet"
brew "topgrade"
brew "translate-shell"
brew "trash"
brew "tree"
brew "tty-clock"
brew "um"
brew "urlview"
brew "vault"
brew "vdirsyncer"
brew "vim"
brew "vtclock"
brew "w3m"
brew "watch"
brew "wget"
brew "yarn"
brew "yq"
brew "zsh"
brew "d12frosted/emacs-plus/emacs-plus", args: ["with-modern-icon", "with-no-titlebar", "without-spacemacs-icon"]
brew "github/gh/gh"
brew "jesseduffield/lazydocker/lazydocker"
brew "rigellute/tap/spotify-tui"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "1password"
cask "appcleaner"
cask "dash"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "firefox"
cask "font-3270-nerd-font"
cask "font-firacode-nerd-font"
cask "font-hack-nerd-font"
cask "font-hermit-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-jetbrainsmono-nerd-font"
cask "font-lekton-nerd-font"
cask "font-monofur-nerd-font"
cask "font-profont-nerd-font-mono"
cask "font-proggyclean-nerd-font-mono"
cask "font-robotomono-nerd-font"
cask "font-sourcecodepro-nerd-font"
cask "google-backup-and-sync"
cask "google-chrome"
cask "grammarly"
cask "image2icon"
cask "insomnia"
cask "iterm2"
cask "kaleidoscope"
cask "karabiner-elements"
cask "keybase"
cask "kindle"
cask "mongotron"
cask "monodraw"
cask "netnewswire"
cask "nordvpn"
cask "notion"
cask "now"
cask "omnidisksweeper"
cask "robo-3t"
cask "sketch"
cask "slack"
cask "spectacle"
cask "spotify"
cask "the-unarchiver"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoomus"
mas "Dato", id: 1470584107
mas "DuckDuckGo Privacy Essentials", id: 1482920575
mas "Grammarly for Safari", id: 1462114288
mas "Honey", id: 1472777122
mas "Keynote", id: 409183694
mas "Mate Translate", id: 1005088137
mas "Numbers", id: 409203825
mas "Octotree Pro", id: 1457450145
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Rosetta Stone", id: 1476088902
mas "Twitter", id: 1482454543
mas "Vimari", id: 1480933944
mas "Wallpaper Wizard", id: 1266674560
mas "Xcode", id: 497799835
