tap "d12frosted/emacs-plus"
tap "denisidoro/tools"
tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "huytd/cask-fonts"
tap "jesseduffield/lazydocker"
tap "mongodb/brew"
tap "pokanop/pokanop"
tap "rigellute/tap"
tap "universal-ctags/universal-ctags"
tap "wtfutil/wtfutil"
cask "xquartz"
brew "asciiquarium"
brew "bash"
brew "bat"
brew "bfg"
brew "broot"
brew "ccat"
brew "cmake"
brew "cmatrix"
brew "coreutils"
brew "cowsay"
brew "ddgr"
brew "deno"
brew "dialog"
brew "diff-so-fancy"
brew "direnv"
brew "duti"
brew "editorconfig"
brew "exa"
brew "fasd"
brew "fd"
brew "tesseract"
brew "ffmpeg"
brew "figlet"
brew "fortune"
brew "fpp"
brew "fzf"
brew "gawk"
brew "gdrive"
brew "gist"
brew "git"
brew "git-flow-avh"
brew "git-lfs"
brew "git-quick-stats"
brew "git-secrets"
brew "gitleaks"
brew "global"
brew "go"
brew "grip"
brew "htop"
brew "hub"
brew "imagemagick"
brew "ispell"
brew "jq"
brew "legit"
brew "less"
brew "lolcat"
brew "lsd"
brew "make"
brew "mas"
brew "mdcat"
brew "mdv"
brew "multimarkdown"
brew "n"
brew "noti"
brew "onefetch"
brew "openvpn", restart_service: true
brew "ossp-uuid"
brew "pandoc"
brew "pkg-config"
brew "png2ico"
brew "poppler"
brew "postgresql", restart_service: true
brew "ranger"
brew "rename"
brew "ripgrep"
brew "ruby"
brew "rust"
brew "shellcheck"
brew "shpotify"
brew "speedtest-cli"
brew "starship"
brew "stow"
brew "surfraw"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "toilet"
brew "topgrade"
brew "translate-shell"
brew "trash"
brew "travis"
brew "tree"
brew "tty-clock"
brew "um"
brew "urlview"
brew "vault"
brew "vdirsyncer"
brew "vim"
brew "vtclock"
brew "w3m"
brew "watch"
brew "wget"
brew "yarn"
brew "yq"
brew "z"
brew "zplug"
brew "zsh"
brew "d12frosted/emacs-plus/emacs-plus@26", link: false
brew "github/gh/gh"
brew "heroku/brew/heroku"
brew "jesseduffield/lazydocker/lazydocker"
brew "mongodb/brew/mongodb-community"
brew "pokanop/pokanop/nostromo"
brew "rigellute/tap/spotify-tui"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "1password"
cask "adobe-creative-cloud"
cask "airtable"
cask "alfred"
cask "appcleaner"
cask "bartender"
cask "brave-browser"
cask "caprine"
cask "dash"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "firefox"
cask "font-3270-nerd-font"
cask "font-anonymice-nerd-font"
cask "font-arimo-nerd-font"
cask "font-aurulentsansmono-nerd-font"
cask "font-bitstreamverasansmono-nerd-font"
cask "font-cascadia"
cask "font-caskaydiacove-nerd-font"
cask "font-codenewroman-nerd-font"
cask "font-cousine-nerd-font"
cask "font-dejavusansmono-nerd-font"
cask "font-droidsansmono-nerd-font"
cask "font-fantasquesansmono-nerd-font"
cask "font-fira-code"
cask "font-firacode-nerd-font"
cask "font-firamono-nerd-font"
cask "font-gomono-nerd-font"
cask "font-hack-nerd-font"
cask "font-hasklig"
cask "font-hasklug-nerd-font"
cask "font-haskplex-nerd"
cask "font-heavydata-nerd-font"
cask "font-hermit-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-inconsolatago-nerd-font"
cask "font-inconsolatalgc-nerd-font"
cask "font-input"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrainsmono-nerd-font"
cask "font-lekton-nerd-font"
cask "font-liberation-nerd-font"
cask "font-materialdesignicons-webfont"
cask "font-meslolg-nerd-font"
cask "font-monofur-nerd-font"
cask "font-monoid-nerd-font"
cask "font-mononoki"
cask "font-mononoki-nerd-font"
cask "font-mplus-nerd-font"
cask "font-noto-nerd-font"
cask "font-press-start2p"
cask "font-profont-nerd-font"
cask "font-proggycleantt-nerd-font"
cask "font-public-sans"
cask "font-roboto"
cask "font-roboto-condensed"
cask "font-roboto-mono"
cask "font-roboto-slab"
cask "font-robotomono-nerd-font"
cask "font-saucecodepro-nerd-font"
cask "font-source-code-pro"
cask "font-sourcecodepro-nerd-font"
cask "font-spacemono-nerd-font"
cask "font-tinos-nerd-font"
cask "font-ubuntu-nerd-font"
cask "font-ubuntumono-nerd-font"
cask "font-vt323"
cask "google-backup-and-sync"
cask "google-chrome"
cask "gpg-suite"
cask "grammarly"
cask "graphql-playground"
cask "image2icon"
cask "insomnia"
cask "istat-menus5"
cask "iterm2"
cask "kaleidoscope"
cask "karabiner-elements"
cask "keybase"
cask "kindle"
cask "mate-translate"
cask "microsoft-edge"
cask "miro-formerly-realtimeboard"
cask "mongotron"
cask "monodraw"
cask "netnewswire"
cask "nordvpn"
cask "notion"
cask "now"
cask "omnidisksweeper"
cask "pgadmin4"
cask "rectangle"
cask "robo-3t"
cask "sequel-pro"
cask "sketch"
cask "slack"
cask "spotify"
cask "the-unarchiver"
cask "tor-browser"
cask "transmission"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
cask "webponize"
cask "whatsapp"
cask "zoomus"
mas "Alto's Adventure", id: 1287752517
mas "Alto's Odyssey", id: 1495097700
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "Bumpr", id: 1166066070
mas "CARROT Weather", id: 993487541
mas "Color Ninja", id: 1494948845
mas "Dato", id: 1470584107
mas "DuckDuckGo Privacy Essentials", id: 1482920575
mas "Grammarly for Safari", id: 1462114288
mas "Honey", id: 1472777122
mas "Instapaper", id: 1481302432
mas "iStat Menus", id: 1319778037
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Marked 2", id: 890031187
mas "Mate Translate", id: 1005088137
mas "Mate Translate", id: 1005088137
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Octotree Pro", id: 1457450145
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "PhotoScissors", id: 1499327097
mas "Pixelmator", id: 407963104
mas "Pocket", id: 568494494
mas "PopClip", id: 445189367
mas "Raindrop.io for Safari", id: 957810159
mas "Reeder", id: 1449412482
mas "Relax Melodies", id: 467103113
mas "ResizeIt", id: 416280139
mas "Rosetta Stone", id: 1476088902
mas "Sip", id: 507257563
mas "Soulver", id: 413965349
mas "Things", id: 904280696
mas "Time Out", id: 402592703
mas "Twitter", id: 1482454543
mas "Vimari", id: 1480933944
mas "Wallpaper Wizard", id: 1266674560
mas "WhatsApp", id: 1147396723
mas "Zen Coloring Book For Adults", id: 1063659855
