#!/usr/bin/env zsh

appearance="$(dark-notify -e | nu --stdin -c 'str trim')"

# Load the scripting addition
sudo yabai --load-sa

## Global Settings
yabai -m config menubar_opacity 1.0                  # 0-1
yabai -m config mouse_follows_focus on               # on | off
yabai -m config focus_follows_mouse autoraise        # autofocus | autoraise | off
yabai -m config display_arrangement_order horizontal # default | vertical | horizontal
yabai -m config window_origin_display focused        # default | focused | cursor
yabai -m config window_placement first_child         # first_child | second_child
yabai -m config window_zoom_persist off              # on | off
yabai -m config window_shadow float                  # true | false | float
yabai -m config window_opacity on                    # on | off
yabai -m config window_opacity_duration 0.1          # 0-1
yabai -m config debug_output off                      # on | off
#yabai -m config insert_feedback_color $"0x88(rose-pine love)"     # 0xAARRGGBB
yabai -m config split_ratio 0.5                      # 0-1
yabai -m config split_type auto                      # vertical | horizontal | auto
yabai -m config mouse_modifier ctrl                  # cmd | alt | shift | ctrl | fn
yabai -m config mouse_drop_action stack              # swap | stack
if [[ "$appearance" == "light" ]]; then
  yabai -m config active_window_opacity 0.97
  yabai -m config normal_window_opacity 0.85
else
  yabai -m config active_window_opacity 0.95
  yabai -m config normal_window_opacity 0.80
fi

# Space Settings
# Settings
padding=16
yabai -m config layout bsp                    # bsp | stack | float
yabai -m config top_padding $padding          # int
yabai -m config bottom_padding $padding       # int
yabai -m config left_padding $padding         # int
yabai -m config right_padding $padding        # int
yabai -m config window_gap $padding           # int
yabai -m config external_bar all:40:0

#
# Labeled Spaces
#
yabai -m space 1 --label main
yabai -m space 2 --label docs
yabai -m space 3 --label design
yabai -m space 4 --label work
yabai -m space 5 --label social
yabai -m space 6 --label other
yabai -m space 7 --label media
yabai -m space 8 --label system

#
# Labeled Displays
#
yabai -m display 1 --label builtin
yabai -m display 2 --label external || true

#
# Rules
#
yabai -m rule --add space=design app=Figma
yabai -m rule --add space=docs app=Dash
yabai -m rule --add space=main app=Emacs
yabai -m rule --add space=main app=qutebrowser
yabai -m rule --add space=media app=Spotify
yabai -m rule --add space=work app=Zoom
yabai -m rule --add space=main app=WezTerm
yabai -m rule --add space=social app=Messages
yabai -m rule --add space=social app=Telegram
yabai -m rule --add space=social app=WhatsApp
yabai -m rule --add space=system app="^CleanMyMac X$"
yabai -m rule --add space=system app="^System Settings$"
yabai -m rule --add space=system app="^ClearVPN$"
yabai -m rule --add space=work app=Slack
yabai -m rule --add space=main app=Neovide

yabai -m signal --add event=space_created action="sketchybar --update"
yabai -m signal --add event=space_changed action="sketchybar --update"
yabai -m signal --add event=space_destroyed action="sketchybar --update"

#
# Signals
#
yabai -m signal --add label=reload-sa event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add label=focus-wez event=window_created action='yabai -m window $YABAI_WINDOW_ID --focus' app='^wezterm-gui$'
yabai -m signal --add event=display_added action="yabai -m display $YABAI_DISPLAY_INDEX --label external"

# Final Instructions
yabai -m rule --apply
sketchybar --reload

# vim: ft=nu
