accordion-padding = 32
after-login-command = []
after-startup-command = ['exec-and-forget sketchybar --reload']
automatically-unhide-macos-hidden-apps = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
start-at-login = true

[exec.env-vars]
  PATH = '${HOME}/bin:/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[key-mapping]
  preset = 'qwerty'

[gaps]
  inner.horizontal = 16
  inner.vertical   = 16
  outer.bottom     = 16
  outer.left       = 16
  outer.right      = 16
  outer.top        = [{ monitor."SAMSUNG" = 56 }, 16]

[workspace-to-monitor-force-assignment]
  1 = "main"
  9 = ["secondary", "main"]

[[on-window-detected]]
  if.app-id                       = "wezterm-gui"
  if.window-title-regex-substring = "spotify_player"
  run                             = ['layout floating']

[mode.main.binding]
  # spellcheck:ignore
  # All possible keys:
  # - Letters.        a, b, c, ..., z
  # - Numbers.        0, 1, 2, ..., 9
  # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
  # - F-keys.         f1, f2, ..., f20
  # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
  #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
  #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
  #                   sectionSign (ISO keyboards only, european keyboards only)
  # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
  #                   keypadMinus, keypadMultiply, keypadPlus
  # - Arrows.         left, down, up, right
  # All possible modifiers: cmd, alt, ctrl, shift

  cmd-ctrl-alt-h = 'focus left'
  cmd-ctrl-alt-i = [
    'exec-and-forget aerospace focus-back-and-forth || aerospace workspace-back-and-forth',
  ]
  cmd-ctrl-alt-j = 'focus down'
  cmd-ctrl-alt-k = 'focus up'
  cmd-ctrl-alt-l = 'focus right'
  cmd-ctrl-alt-m = 'fullscreen'
  cmd-ctrl-alt-n = 'workspace next'
  cmd-ctrl-alt-o = 'focus-monitor --wrap-around next'
  cmd-ctrl-alt-p = 'workspace prev'
  cmd-ctrl-alt-slash = 'layout accordion tiles'
  cmd-ctrl-alt-space = 'mode focus'
  f13 = 'mode focus'

[mode.focus.binding]
  1 = 'workspace 1'
  2 = 'workspace 2'
  3 = 'workspace 3'
  4 = 'workspace 4'
  5 = 'workspace 5'
  6 = 'workspace 6'
  7 = 'workspace 7'
  8 = 'workspace 8'
  9 = 'workspace 9'
  a = 'layout accordion'
  alt-1 = 'summon-workspace 1'
  alt-2 = 'summon-workspace 2'
  alt-3 = 'summon-workspace 3'
  alt-4 = 'summon-workspace 4'
  alt-5 = 'summon-workspace 5'
  alt-6 = 'summon-workspace 6'
  alt-7 = 'summon-workspace 7'
  alt-8 = 'summon-workspace 8'
  alt-9 = 'summon-workspace 9'
  comma = 'layout horizontal vertical'
  enter = "fullscreen"
  equal = 'resize smart +50'
  esc = 'mode main'
  f = 'layout floating tiling'
  h = 'focus left'
  i = 'exec-and-forget aerospace focus-back-and-forth || aerospace workspace-back-and-forth'
  j = 'focus down'
  k = 'focus up'
  l = 'focus right'
  m = 'mode move'
  minus = 'resize smart -50'
  n = 'workspace next'
  o = 'focus-monitor --wrap-around next'
  p = 'workspace prev'
  r = [
    'reload-config',
    'exec-and-forget sketchybar --reload',
    'exec-and-forget noti -t "aerospace" -m "config relaoded!"',
  ]
  slash = 'layout accordion tiles'
  t = 'layout tiles'
  tab = 'workspace-back-and-forth'

[mode.move.binding]
  1 = [
    'move-node-to-workspace 1',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  2 = [
    'move-node-to-workspace 2',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  3 = [
    'move-node-to-workspace 3',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  4 = [
    'move-node-to-workspace 4',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  5 = [
    'move-node-to-workspace 5',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  6 = [
    'move-node-to-workspace 6',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  7 = [
    'move-node-to-workspace 7',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  8 = [
    'move-node-to-workspace 8',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  9 = [
    'move-node-to-workspace 9',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  esc = [
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  h = [
    'move left',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  j = [
    'move down',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  k = [
    'move up',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  l = [
    'move right',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  n = [
    "move-node-to-workspace next",
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  o = [
    'move-workspace-to-monitor --wrap-around next',
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  p = [
    "move-node-to-workspace prev",
    'mode focus',
    'exec-and-forget sketchybar --trigger aerospace_workspace_change',
  ]
  shift-h = 'join-with left'
  shift-j = 'join-with down'
  shift-k = 'join-with up'
  shift-l = 'join-with right'
