auto_sync = true
dialect = "us"
enter_accept = true
filter_mode = "session"
filter_mode_shell_up_keybinding = "session"
inline_height = 10
keymap_mode = "vim-normal"
search_mode = "fuzzy"
style = "compact"
sync_frequency = "1h"

[theme]
name = "autumn"
