#!/usr/bin/env bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

source "$CONFIG_DIR/colors.sh"
FONT="GeistMono Nerd Font Propo"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar \
	position=top \
	height=40 \
	blur_radius=30 \
	"color=$(color 0 55)"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
	padding_left=5
	padding_right=5
	icon.font="${FONT}:Normal:18.0"
	label.font="${FONT}:Normal:16.0"
	"icon.color=$(color 16)"
	"label.color=$(color 16)"
	icon.padding_left=4
	icon.padding_right=4
	label.padding_left=4
	label.padding_right=4
	"alias.color=$(color 16)"
	alias.scale=1.0
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"; do
	sid="$(($i + 1))"
	space=(
		space="$sid"
		icon="${SPACE_ICONS[i]}"
		icon.font.size="16.0"
		icon.padding_left=8
		icon.padding_right=8
		"icon.color=$(color 8)"
		"background.color=$(color 4 44)"
		background.corner_radius=5
		background.height=25
		label.drawing=off
		script="$PLUGIN_DIR/space.sh"
		click_script="hs -c 'hs.spaces.gotoSpace(hs.spaces.spacesForScreen()[$sid])'"
	)
	sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
	--set chevron icon="" label.drawing=off icon.color="$(color 5)" \
	--add item front_app left \
	--set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" label.color="$(color 5)" \
	--subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
	--set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change \
	--add item battery right \
	--set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
	--subscribe battery system_woke power_source_change

ALIASES=(
	"Tailscale,Item-0"
	"TextInputMenuAgent,Item-0"
	"Control Center,FocusModes"
)
for i in "${ALIASES[@]}"; do
	sketchybar --add alias "$i" right \
		--set "$i" background.padding_left=0 \
		background.padding_right=8 \
		label.drawing=off \
		icon.drawing=off
done

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
