#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
FONT="BlexMono Nerd Font Propo"

source ./colors.sh

# Setup bar
args=(
	--bar
	position=top
	height=40
	blur_radius=30
	color="$(color -a 88 background)"
)

sketchybar "${args[@]}"

# Setup defaults
args=(
	--default
	padding_left=3
	padding_right=3
	icon.font="${FONT}:Normal:18.0"
	label.font="${FONT}:Normal:16.0"
	icon.color="$(color purple)"
	label.color="$(color foreground)"
	icon.padding_left=8
	icon.padding_right=4
	label.padding_left=4
	label.padding_right=8
	alias.color="$(color cyan)"
	alias.scale=1.0
)

# Setup  AeroSpace spaces
args+=(
	--add event aerospace_workspace_change
	--add item aerospace left
	--set aerospace
	script="$PLUGIN_DIR/aerospace.sh"
	drawing=off
	--subscribe aerospace aerospace_workspace_change
)
for sid in $(aerospace list-workspaces --all); do
	args+=(
		--add item space."$sid" left
		--set space."$sid"
		background.color="$(color -a 33 green)"
		background.corner_radius=5
		background.drawing=off
		background.height=20
		label.y_offset=1
		icon.y_offset=1
		background.padding_left=0
		background.padding_right=0
		click_script="aerospace workspace $sid"
		icon.color="$(color -a 00 selection)"
		icon.highlight_color="$(color -a 44 green)"
		icon.padding_left=4
		icon.padding_right=0
		icon=•
		label.color="$(color comment)"
		label.font.size=14.0
		label.highlight_color="$(color green)"
		label.padding_left=8
		label.padding_right=6
		label="$sid"
		padding_left=0
		padding_right=0
	)
done

# Setup chevron
args+=(
	--add item chevron left
	--set chevron icon=""
	label.drawing=off
	icon.color="$(color red)"
	icon.padding_left=12
)

# Setup front app
args+=(
	--add item front_app left
	--set front_app
	icon.drawing=off
	script="$PLUGIN_DIR/front_app.sh"
	label.color="$(color pink)"
	--subscribe front_app front_app_switched
)

# Setup AeroSpace Modes
args+=(
	--add event aerospace_mode_change
	--add item aerospace.mode left
	--subscribe aerospace.mode aerospace_mode_change
	--set aerospace.mode
	drawing=off
	icon=""
	icon.color="$(color cyan)"
	label.color="$(color yellow)"
	update_freq=1
	script="$PLUGIN_DIR/aerospace_mode.sh"
	click_script="aerospace mode main; sketchybar --trigger aerospace_mode_change MODE=main"
)

# Setup clock
args+=(
	--add item clock right
	--set clock
	display=active
	update_freq=10
	icon= script="$PLUGIN_DIR/clock.sh"
)

# Setup volume
args+=(
	--add item volume right
	--set volume script="$PLUGIN_DIR/volume.sh"
	display=active
	--subscribe volume volume_change
)

# Setup battery
args+=(
	--add item battery right
	--set battery
	display=active
	update_freq=120
	script="$PLUGIN_DIR/battery.sh"
	--subscribe battery system_woke power_source_change
)

aliases=(
	"Tailscale,Item-0"
	"TextInputMenuAgent,Item-0"
	"Control Center,FocusModes"
	"AeroSpace,Item-0"
)
for alias in "${aliases[@]}"; do
	args+=(
		--add alias "$alias" right
		--set "$alias"
		background.padding_left=0
		background.padding_right=8
		display=active
		label.drawing=off
		icon.drawing=off
	)
done

args+=(
	--add item spotify q
	--set spotify
	display=1
	drawing=off
	label.font.size=12.0
	icon=""
	icon.color="$(color green)"
	label.color="$(color yellow)"
	background.corner_radius=4
	background.height=24
	label.padding_right=8
	scroll_texts=on
	label.scroll_duration=300
	icon.padding_left=8
	background.color="$(color -a 33 green)"
	script="$PLUGIN_DIR/spotify.sh"
	update_freq=5
	click_script="\
    wezterm \
      --config window_close_confirmation=\'NeverPrompt\' \
      --config window_decorations=\'RESIZE\' \
      --config enable_tab_bar=false \
      start \
      --domain unix \
      --attach \
      --workspace spotify \
      spotify_player"
)

sketchybar "${args[@]}"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
