#!/usr/bin/env zsh

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
FONT="BlexMono Nerd Font"

if [[ "$(dark-notify -e)" == "dark" ]]; then
	base="191724"
	surface="1f1d2e"
	overlay="26233a"
	muted="6e6a86"
	subtle="908caa"
	text="e0def4"
	love="eb6f92"
	gold="f6c177"
	rose="ebbcba"
	pine="31748f"
	foam="9ccfd8"
	iris="c4a7e7"
	highlight_low="21202e"
	highlight_med="403d52"
	highlight_high="524f67"
else
	base="faf4ed"
	surface="fffaf3"
	overlay="f2e9e1"
	muted="9893a5"
	subtle="797593"
	text="575279"
	love="b4637a"
	gold="ea9d34"
	rose="d7827e"
	pine="286983"
	foam="56949f"
	iris="907aa9"
	highlight_low="f4ede8"
	highlight_med="dfdad9"
	highlight_high="cecacd"
fi

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=40 blur_radius=30 color=0xcc$surface

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
	padding_left=5
	padding_right=5
	icon.font="$FONT:Bold:17.0"
	label.font="$FONT:Bold:14.0"
	icon.color=0xff$foam
	label.color=0xff$text
	icon.padding_left=4
	icon.padding_right=4
	label.padding_left=4
	label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Aerospace Integration #####

sketchybar --add event aerospace_workspace_change

tyepset -A labels icons
icons=(
	
  
  
  
	󰍺
)
labels=(
	main
	alt
  docs
	media
	external
)
index=1
for sid in $(aerospace list-workspaces --all); do
	sketchybar --add item space.$sid left \
		--subscribe space.$sid aerospace_workspace_change \
		--set space.$sid \
		icon.font="$FONT:Bold:18.0" \
		label.font="$FONT:Bold:14.0" \
		icon.color=0xff$foam \
		label.color=0xff$text \
		background.color=0x88$gold \
		background.corner_radius=5 \
		background.height=20 \
		background.drawing=off \
		icon="$icons[$sid]" \
		label="$sid $labels[$sid]" \
		label.padding_left = 4 \
		label.padding_right = 4 \
		click_script="aerospace workspace $sid" \
		script="$CONFIG_DIR/plugins/aerospace.sh $sid"

	index=$(($index + 1))
done

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
	--set chevron icon="" label.drawing=off \
	--add item front_app left \
	--set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
	--subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar \
	--add item clock right \
	--set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change \
	--add item battery right \
	--set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
	--subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
