#:schema https://mise.jdx.dev/schema/mise-task.json

[dev]
tools.hivemind = "latest"
run = "hivemind"

[reload]
run = "sketchybar --reload"

[restart]
run = "brew services restart sketchybar"

["tail:out"]
run = '''
#!/usr/bin/env nu
plugin use formats
open --raw {{vars.plist}} | from plist | get StandardOutPath | tail -f $in
'''

["tail:err"]
# nu
run = '''
#!/usr/bin/env nu
plugin use formats
open --raw {{vars.plist}} | from plist | get StandardErrorPath | tail -f $in
'''
