[task_config]
includes = ["mise-tasks.toml"]

[vars]
plist = "~/Library/LaunchAgents/homebrew.mxcl.sketchybar.plist"

[hooks]
enter = "mise install"

[tools]
"aqua:zyedidia/eget" = "latest"
hivemind = "latest"
overmind = "latest"
"pipx:jc" = "latest"
watchexec = "latest"
