# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-fpp'
set -g @plugin 'tmux-plugins/tmux-urlview'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'jimeh/tmux-themepack'

# Plugin Settings
set -g @emulate-scroll-for-no-mouse-alternate-buffer 'on'
set -g @themepack 'powerline/double/blue'

run '~/.tmux/plugins/tpm/tpm'

# Custom Settings
setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -s default-terminal screen-256color
set -as terminal-overrides ",*-256color:Tc"
set -g detach-on-destroy off

# Custom Bindings
bind-key C-c new-window -c '#{pane_current_path}'
bind-key C-l send-keys 'C-l'
