# vim: fdm=marker fdl=1

# List TMUX Plugins {{{
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#}}}

# Initialize Plugin Manager (keep at bottom) {{{
run -b '~/.tmux/plugins/tpm/tpm'
#}}}
