#   dP                                
#   88                                
# d8888P 88d8b.d8b. dP    dP dP.  .dP 
#   88   88'`88'`88 88    88  `8bd8'  
#   88   88  88  88 88.  .88  .d88b.  
#   dP   dP  dP  dP `88888P' dP'  `dP 

# tpm {{{
set -g @plugin 'tmux-plugins/tpm'
#}}}

# tmux-plugins/tmux-sensible {{{
set -g @plugin 'tmux-plugins/tmux-sensible'
#}}}

# tmux-plugins/tmux-pain-control {{{
set -g @plugin 'tmux-plugins/tmux-pain-control'
#}}}

# tmux-plugins/tmux-yank {{{
set -g @plugin 'tmux-plugins/tmux-yank'
#}}}

# tmux-plugins/tmux-open {{{
set -g @plugin 'tmux-plugins/tmux-open'
#}}}

# tmux-plugins/tmux-urlview {{{
set -g @plugin 'tmux-plugins/tmux-urlview'
#}}}

# tmux-plugins/tmux-sidebar {{{
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @sidebar-tree-command 'lsd --tree --color=always --icon=always'
set -g @sidebar-tree 'e'
#}}}

# tmux-plugins/tmux-resurrect {{{
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
# }}}

# tmux-plugins/tmux-continuum {{{
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'iterm,fullscreen'
#}}}

# tmux-plugins/tmux-fpp {{{
set -g @plugin 'tmux-plugins/tmux-fpp'
set -g @fpp-key 'C-f'
#}}}

# christoomey/vim-tmux-navigator {{{
set -g @plugin 'christoomey/vim-tmux-navigator'
# }}}

# jimeh/tmux-themepack {{{
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/block/gray'
#}}}

# Personal Settings{{{
set -g mouse on
set -g base-index 1
# }}}

# Initialize Plugin Manager (keep at bottom) {{{

# Any keybinding overrides must be run after loading TPM, so we use the
# `if-shell` command to ensure these bindings run after the exit code from
# running TPM's loader.

if-shell -b '~/.tmux/plugins/tpm/tpm' \
  "bind C-l send-keys 'C-l'"
#}}}

# vim: fdm=marker fdl=0
