[tools]
go = "latest"
node = "latest"
just = "latest"
ruby = "latest"
"npm:opencommit" = "latest"
"go:github.com/mattn/bsky" = "latest"
usql = "latest"
"cargo:scooter" = "latest"
usage = "latest"
neovim = "latest"
"npm:zx" = "latest"
"npm:prettier" = "latest"
chezmoi = "latest"
"ubi:Nukesor/pueue" = "latest"
"ubi:nushell/nushell" = { version = "latest", exe = "nu" }
"ubi:aquaproj/aqua" = "latest"

[settings]
experimental = true

[env]

[tasks]

[tasks.search]
run = "aqua g"
