[tools]
go = "latest"
node = "latest"
just = "latest"
ruby = "latest"
"cargo:pueue" = "latest"
"npm:opencommit" = "latest"
"go:github.com/mattn/bsky" = "latest"
usql = "latest"
"cargo:scooter" = "latest"

[settings]
experimental = true
