[settings]
experimental = true

[tools]
age = "latest"
aqua = "latest"
"aqua:YS-L/csvlens" = "latest"
"aqua:charmbracelet/mods" = "latest"
"aqua:chmln/sd" = "latest"
"aqua:hatoo/oha" = "latest"
"aqua:mr-karan/doggo" = "latest"
"aqua:ouch-org/ouch" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
ast-grep = "latest"
bat = "latest"
bsky = "latest"
cargo-binstall = "latest"
"cargo:hanshuaikang/nping" = "latest"
"cargo:https://github.com/Magic-JD/is-fast" = "latest"
"cargo:tock" = "latest"
"cargo:yshavit/mdq" = "latest"
chezmoi = "latest"
cocogitto = "latest"
duckdb = "latest"
fd = "latest"
fx = "latest"
fzf = "latest"
gh = "latest"
gitu = "latest"
glow = "latest"
go = "latest"
gum = "latest"
jc = "latest"
jd = "latest"
jq = "latest"
jqp = "latest"
ls-lint = "latest"
macchina = "latest"
neovim = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:gitignore" = "latest"
"npm:opencommit" = "latest"
"pipx:harlequin" = "latest"
"pipx:httpie" = "latest"
"pipx:linode-cli" = { version = "latest", extras = '"--with boto3"' }
"pipx:open-interpreter" = "latest"
"pipx:posting" = "latest"
"pipx:rich-cli" = "latest"
"pipx:terminal-colors" = "latest"
"pipx:tmuxp" = "latest"
"pipx:xonsh" = { version = "latest", uvx_args = "--with gnureadline" }
pup = "latest"
python = "3.12"
rg = "latest"
ruby = "latest"
rust = "latest"
sops = "latest"
tz = "latest"
"ubi:Slackadays/Clipboard" = { version = "latest", exe = "cb" }
"ubi:sinclairtarget/git-who" = "latest"
uv = "latest"
vivid = "latest"
volgo = "latest"
wrk = "latest"
yq = "latest"
zellij = "latest"

[hooks.enter]
script = 'eval "$(chezmoi generate zsh)"'

[alias]
pup = "go:github.com/ericchiang/pup"
bsky = "go:github.com/mattn/bsky"
volgo = "go:github.com/elliot40404/volgo/cmd/volgo"
tz = "go:github.com/oz/tz"
macchina = "aqua:Macchina-CLI/macchina"

[env]
_.file = "~/.config/mise/env.sops.yaml"
IS_FAST_CONFIG_PATH = "~/.config/is-fast/config.toml"
OCO_ONE_LINE_COMMIT = "true"
