[tools]
go = "latest"
node = "latest"
just = "latest"
ruby = "latest"
"npm:opencommit" = "latest"
"cargo:scooter" = "latest"
usage = "latest"
neovim = "latest"
"npm:zx" = "latest"
"npm:prettier" = "latest"
chezmoi = "latest"
"ubi:aquaproj/aqua" = "latest"
zellij = "latest"
"aqua:nushell/nushell" = "latest"
"cargo:pueue" = "latest"

[settings]
experimental = true

[env]

[tasks]

[tasks.search]
run = "aqua g"
