[tools]
go = "latest"
node = "latest"
just = "latest"
ruby = "latest"
"cargo:pueue" = "latest"
"npm:opencommit" = "latest"
"go:github.com/mattn/bsky" = "latest"
usql = "latest"
"cargo:scooter" = "latest"
usage = "latest"
neovim = "latest"
"cargo:nu" = "latest"
"npm:zx" = "latest"
"npm:prettier" = "latest"

[settings]
experimental = true

[env]
