[tools]
go = "latest"
node = "latest"
just = "latest"
ruby = "latest"
"npm:opencommit" = "latest"
"cargo:scooter" = "latest"
usage = "latest"
neovim = "latest"
"npm:zx" = "latest"
"npm:prettier" = "latest"
chezmoi = "latest"
"ubi:aquaproj/aqua" = "latest"
zellij = "latest"
"cargo:pueue" = "latest"
"npm:better-commits" = "latest"
"aqua:sharkdp/vivid" = "latest"
starship = "latest"
python = "latest"
"pipx:jc" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"aqua:denisidoro/navi" = "latest"
"ubi:oz/tz" = "latest"
"pipx:linode-cli" = "latest"
opentofu = "latest"

[tools."ubi:carapace-sh/carapace-bin"]
version = "latest"
exe = "carapace"

[settings]
experimental = true

[env]

[tasks]
