[settings]
experimental = true

[tools]
age = "latest"
aqua = "latest"
"aqua:YS-L/csvlens" = "latest"
"aqua:charmbracelet/mods" = "latest"
"aqua:chmln/sd" = "latest"
"aqua:hatoo/oha" = "latest"
"aqua:mr-karan/doggo" = "latest"
"aqua:ouch-org/ouch" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
ast-grep = "latest"
bat = "latest"
cargo-binstall = "latest"
"cargo:hanshuaikang/nping" = "latest"
"cargo:tock" = "latest"
"cargo:yshavit/mdq" = "latest"
chezmoi = "latest"
cocogitto = "latest"
duckdb = "latest"
fd = "latest"
fx = "latest"
fzf = "latest"
gh = "latest"
gitu = "latest"
glow = "latest"
go = "latest"
gum = "latest"
jc = "latest"
jd = "latest"
jq = "latest"
jqp = "latest"
ls-lint = "latest"
macchina = "latest"
neovim = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:gitignore" = "latest"
"npm:opencommit" = "latest"
"pipx:harlequin" = "latest"
"pipx:httpie" = "latest"
"pipx:linode-cli" = { version = "latest", extras = '"--with boto3"' }
"pipx:open-interpreter" = "latest"
"pipx:posting" = "latest"
"pipx:rich-cli" = "latest"
"pipx:terminal-colors" = "latest"
"pipx:tmuxp" = "latest"
"pipx:xonsh" = { version = "latest", uvx_args = "--with gnureadline" }
"go:github.com/ericchiang/pup" = "latest"
"aqua:Macchina-CLI/macchina" = "latest"
python = "3.12"
rg = "latest"
ruby = "latest"
rust = "latest"
sops = "latest"
"ubi:Slackadays/Clipboard" = { version = "latest", exe = "cb" }
"ubi:sinclairtarget/git-who" = "latest"
uv = "latest"
vivid = "latest"
"go:github.com/elliot40404/volgo/cmd/volgo" = "latest"
wrk = "latest"
yq = "latest"
zellij = "latest"
"go:github.com/oz/tz" = "latest"
choose = "latest"

[hooks.enter]
script = 'eval "$(chezmoi generate zsh)"'

[env]
_.file = "~/.config/mise/env.sops.yaml"
FZF_DEFAULT_OPTS = """\
--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 \
--color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 \
--color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 \
--color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4\
"""
