[settings]
experimental = true

[tools]
age = "latest"
aqua = "latest"
"aqua:YS-L/csvlens" = "latest"
"aqua:chmln/sd" = "latest"
"aqua:hatoo/oha" = "latest"
"aqua:mr-karan/doggo" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
ast-grep = "latest"
bat = "latest"
bsky = "latest"
"cargo:hanshuaikang/nping" = "latest"
"cargo:tock" = "latest"
"cargo:yshavit/mdq" = "latest"
chezmoi = "latest"
cocogitto = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
go = "latest"
gum = "latest"
jc = "latest"
jd = "latest"
jq = "latest"
jqp = "latest"
macchina = "latest"
neovim = "latest"
node = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:gitignore" = "latest"
"pipx:harlequin" = "latest"
"pipx:httpie" = "latest"
"pipx:linode-cli" = { version = "latest", extras = '"--with boto3"' }
"pipx:posting" = "latest"
"pipx:rich-cli" = "latest"
"pipx:terminal-colors" = "latest"
"pipx:tmuxp" = "latest"
"pipx:xonsh" = { version = "latest", uvx_args = "--with gnureadline" }
pup = "latest"
python = "3.12"
rg = "latest"
ruby = "latest"
rust = "latest"
tz = "latest"
uv = "latest"
vivid = "latest"
volgo = "latest"
wrk = "latest"
yq = "latest"
zellij = "latest"

[hooks.enter]
script = 'eval "$(chezmoi generate zsh)"'

[alias]
pup = "go:github.com/ericchiang/pup"
bsky = "go:github.com/mattn/bsky"
volgo = "go:github.com/elliot40404/volgo/cmd/volgo"
tz = "go:github.com/oz/tz"
macchina = "aqua:Macchina-CLI/macchina"
