[settings]
experimental = true

[tools]
aqua = "latest"
"aqua:mr-karan/doggo" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
fzf = "latest"
go = "latest"
"go:github.com/elliot40404/volgo/cmd/volgo" = "latest"
jc = "latest"
neovim = "latest"
node = "latest"
"npm:gitignore" = "latest"
"pipx:linode-cli" = { version = "latest", extras = '"--with boto3"' }
python = "latest"
ruby = "latest"
rust = "latest"
uv = "latest"
vivid = "latest"
zellij = "latest"
