[settings]
experimental = true

[tools]
age = "latest"
aqua = "latest"
"aqua:YS-L/csvlens" = "latest"
"aqua:chmln/sd" = "latest"
"aqua:mr-karan/doggo" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
ast-grep = "latest"
bat = "latest"
"cargo:hanshuaikang/nping" = "latest"
"cargo:yshavit/mdq" = "latest"
chezmoi = "latest"
cocogitto = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
go = "latest"
"go:github.com/elliot40404/volgo/cmd/volgo" = "latest"
"go:github.com/ericchiang/pup" = "latest"
"go:github.com/oz/tz" = "latest"
gum = "latest"
jc = "latest"
jd = "latest"
jnv = "latest"
jq = "latest"
jqp = "latest"
neovim = "latest"
node = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:gitignore" = "latest"
"pipx:httpie" = "latest"
"pipx:linode-cli" = { version = "latest", extras = '"--with boto3"' }
"pipx:posting" = "latest"
"pipx:tmuxp" = "latest"
python = "3.12"
rg = "latest"
ruby = "latest"
rust = "latest"
uv = "latest"
vivid = "latest"
yq = "latest"
zellij = "latest"

[hooks.enter]
script = 'eval "$(chezmoi generate zsh)"'
