[settings]
experimental = true

[tools]
age = "latest"
aqua = "latest"
"aqua:chmln/sd" = "latest"
"aqua:mr-karan/doggo" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
bat = "latest"
chezmoi = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
go = "latest"
"go:github.com/elliot40404/volgo/cmd/volgo" = "latest"
"go:github.com/oz/tz" = "latest"
jc = "latest"
jd = "latest"
jq = "latest"
neovim = "latest"
node = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:gitignore" = "latest"
"pipx:linode-cli" = { version = "latest", extras = '"--with boto3"' }
python = "latest"
rg = "latest"
ruby = "latest"
rust = "latest"
uv = "latest"
vivid = "latest"
yq = "latest"
zellij = "latest"
