[settings]
experimental = true

[tools]
go = "latest"
"go:github.com/elliot40404/volgo/cmd/volgo" = "latest"
neovim = "latest"
node = "latest"
"npm:gitignore" = "latest"
"pipx:linode-cli" = { version = "latest", extras = '"--with boto3"' }
python = "latest"
ruby = "latest"
rust = "latest"
uv = "latest"
zellij = "latest"
