#!/usr/bin/env zsh

urls=(
  facebook.com
  twitter.com
  instagram.com
  linkedin.com
  bsky.app
  hachyderm.io
  reddit.com
)

for url in $urls; do
  echo "open -t https://$url ;; tab-focus -7" >> "$QUTE_FIFO"
done
