#!/usr/bin/env zsh

urls=(
  fastmail.com
  facebook.com
  instagram.com
  linkedin.com
  bsky.app
  hachyderm.io
  reddit.com
  twitter.com
)

for url in $urls; do
  echo "open -t https://$url" >> "$QUTE_FIFO"
done
